// FIFA World Cup 2026 — squads.
// Real announced 26-man squads are sourced from ESPN's squad-list tracker
// (June 2026). Teams whose final list could not be verified are marked
// { announced: false } and shown as "Final squad to be announced soon".
// p = position: GK | DEF | MID | FWD ; c = club at selection.

export const squads = {
  // ---------------- GROUP A ----------------
  'Mexico': {
    coach: 'Javier Aguirre',
    players: [
      { n: 'Carlos Acevedo', p: 'GK', c: 'Santos Laguna' },
      { n: 'Guillermo Ochoa', p: 'GK', c: 'AEL Limassol' },
      { n: 'Raúl Rangel', p: 'GK', c: 'Guadalajara' },
      { n: 'Jesús Gallardo', p: 'DEF', c: 'Toluca' },
      { n: 'Israel Reyes', p: 'DEF', c: 'Club América' },
      { n: 'César Montes', p: 'DEF', c: 'Lokomotiv Moscow' },
      { n: 'Jorge Sánchez', p: 'DEF', c: 'PAOK' },
      { n: 'Johan Vásquez', p: 'DEF', c: 'Genoa' },
      { n: 'Mateo Chávez', p: 'DEF', c: 'AZ Alkmaar' },
      { n: 'Gilberto Mora', p: 'MID', c: 'Tijuana' },
      { n: 'Edson Álvarez', p: 'MID', c: 'Fenerbahçe' },
      { n: 'Orbelín Pineda', p: 'MID', c: 'AEK Athens' },
      { n: 'Luis Romo', p: 'MID', c: 'Guadalajara' },
      { n: 'Brian Gutiérrez', p: 'MID', c: 'Guadalajara' },
      { n: 'Obed Vargas', p: 'MID', c: 'Atlético Madrid' },
      { n: 'César Huerta', p: 'MID', c: 'Anderlecht' },
      { n: 'Luis Chávez', p: 'MID', c: 'Dynamo Moscow' },
      { n: 'Erik Lira', p: 'MID', c: 'Cruz Azul' },
      { n: 'Álvaro Fidalgo', p: 'MID', c: 'Real Betis' },
      { n: 'Roberto Alvarado', p: 'MID', c: 'Guadalajara' },
      { n: 'Armando González', p: 'FWD', c: 'Guadalajara' },
      { n: 'Raúl Jiménez', p: 'FWD', c: 'Fulham' },
      { n: 'Julián Quiñones', p: 'FWD', c: 'Al-Qadsiah' },
      { n: 'Santiago Giménez', p: 'FWD', c: 'AC Milan' },
      { n: 'Guillermo Martínez', p: 'FWD', c: 'Pumas UNAM' },
      { n: 'Alexis Vega', p: 'FWD', c: 'Toluca' },
    ],
  },
  'South Africa': {
    coach: 'Hugo Broos',
    players: [
      { n: 'Ronwen Williams', p: 'GK', c: 'Mamelodi Sundowns' },
      { n: 'Ricardo Goss', p: 'GK', c: 'Mamelodi Sundowns' },
      { n: 'Sipho Chaine', p: 'GK', c: 'Orlando Pirates' },
      { n: 'Khuliso Mudau', p: 'DEF', c: 'Mamelodi Sundowns' },
      { n: 'Nkosinathi Sibisi', p: 'DEF', c: 'Orlando Pirates' },
      { n: 'Ime Okon', p: 'DEF', c: 'Hannover 96' },
      { n: 'Khulumani Ndamane', p: 'DEF', c: 'Mamelodi Sundowns' },
      { n: 'Aubrey Modiba', p: 'DEF', c: 'Mamelodi Sundowns' },
      { n: 'Samukelo Kabini', p: 'DEF', c: 'Molde' },
      { n: 'Thabang Matuludi', p: 'DEF', c: 'Polokwane City' },
      { n: 'Olwethu Makhanya', p: 'DEF', c: 'Philadelphia Union' },
      { n: 'Bradley Cross', p: 'DEF', c: 'Kaizer Chiefs' },
      { n: 'Mbekezeli Mbokazi', p: 'DEF', c: 'Chicago Fire' },
      { n: 'Teboho Mokoena', p: 'MID', c: 'Mamelodi Sundowns' },
      { n: 'Thalente Mbatha', p: 'MID', c: 'Orlando Pirates' },
      { n: 'Yaya Sithole', p: 'MID', c: 'Tondela' },
      { n: 'Jayden Adams', p: 'MID', c: 'Mamelodi Sundowns' },
      { n: 'Oswin Appollis', p: 'FWD', c: 'Orlando Pirates' },
      { n: 'Iqraam Rayners', p: 'FWD', c: 'Mamelodi Sundowns' },
      { n: 'Tshepang Moremi', p: 'FWD', c: 'Orlando Pirates' },
      { n: 'Relebohile Mofokeng', p: 'FWD', c: 'Orlando Pirates' },
      { n: 'Evidence Makgopa', p: 'FWD', c: 'Orlando Pirates' },
      { n: 'Themba Zwane', p: 'FWD', c: 'Mamelodi Sundowns' },
      { n: 'Lyle Foster', p: 'FWD', c: 'Burnley' },
      { n: 'Thapelo Maseko', p: 'FWD', c: 'AEL Limassol' },
    ],
  },
  'Korea Republic': {
    coach: 'Hong Myung-bo',
    players: [
      { n: 'Jo Hyun-woo', p: 'GK', c: 'Ulsan HD' },
      { n: 'Kim Seung-gyu', p: 'GK', c: 'FC Tokyo' },
      { n: 'Song Bum-keun', p: 'GK', c: 'Jeonbuk Hyundai' },
      { n: 'Kim Min-jae', p: 'DEF', c: 'Bayern Munich' },
      { n: 'Jo Yu-min', p: 'DEF', c: 'Sharjah' },
      { n: 'Lee Han-beom', p: 'DEF', c: 'Midtjylland' },
      { n: 'Kim Tae-hyun', p: 'DEF', c: 'Kashima Antlers' },
      { n: 'Park Jin-seop', p: 'DEF', c: 'Zhejiang FC' },
      { n: 'Lee Ki-hyeok', p: 'DEF', c: 'Gangwon FC' },
      { n: 'Lee Tae-seok', p: 'DEF', c: 'Austria Vienna' },
      { n: 'Seol Young-woo', p: 'DEF', c: 'Red Star Belgrade' },
      { n: 'Jens Castrop', p: 'DEF', c: 'Borussia Mönchengladbach' },
      { n: 'Kim Moon-hwan', p: 'DEF', c: 'Daejeon Hana Citizen' },
      { n: 'Yang Hyun-jun', p: 'MID', c: 'Celtic' },
      { n: 'Paik Seung-ho', p: 'MID', c: 'Birmingham City' },
      { n: 'Hwang In-beom', p: 'MID', c: 'Feyenoord' },
      { n: 'Kim Jin-kyu', p: 'MID', c: 'Jeonbuk Hyundai' },
      { n: 'Bae Jun-ho', p: 'MID', c: 'Stoke City' },
      { n: 'Um Ji-sung', p: 'MID', c: 'Swansea City' },
      { n: 'Hwang Hee-chan', p: 'MID', c: 'Wolverhampton' },
      { n: 'Lee Dong-gyeong', p: 'MID', c: 'Ulsan HD' },
      { n: 'Lee Jae-sung', p: 'MID', c: 'Mainz 05' },
      { n: 'Lee Kang-in', p: 'MID', c: 'Paris Saint-Germain' },
      { n: 'Oh Hyeon-gyu', p: 'FWD', c: 'Beşiktaş' },
      { n: 'Son Heung-min', p: 'FWD', c: 'LAFC' },
      { n: 'Cho Gue-sung', p: 'FWD', c: 'Midtjylland' },
    ],
  },
  'Czechia': { coach: 'Miroslav Koubek', announced: false },

  // ---------------- GROUP B ----------------
  'Canada': {
    coach: 'Jesse Marsch',
    players: [
      { n: 'Dayne St. Clair', p: 'GK', c: 'Inter Miami' },
      { n: 'Maxime Crépeau', p: 'GK', c: 'Orlando City' },
      { n: 'Owen Goodman', p: 'GK', c: 'Barnsley' },
      { n: 'Moïse Bombito', p: 'DEF', c: 'Nice' },
      { n: 'Derek Cornelius', p: 'DEF', c: 'Rangers' },
      { n: 'Alphonso Davies', p: 'DEF', c: 'Bayern Munich' },
      { n: 'Luc de Fougerolles', p: 'DEF', c: 'FCV Dender' },
      { n: 'Alistair Johnston', p: 'DEF', c: 'Celtic' },
      { n: 'Alfie Jones', p: 'DEF', c: 'Middlesbrough' },
      { n: 'Richie Laryea', p: 'DEF', c: 'Toronto FC' },
      { n: 'Niko Sigur', p: 'DEF', c: 'Hajduk Split' },
      { n: 'Joel Waterman', p: 'DEF', c: 'Chicago Fire' },
      { n: 'Ali Ahmed', p: 'MID', c: 'Norwich City' },
      { n: 'Tajon Buchanan', p: 'MID', c: 'Villarreal' },
      { n: 'Mathieu Choinière', p: 'MID', c: 'LAFC' },
      { n: 'Stephen Eustáquio', p: 'MID', c: 'LAFC' },
      { n: 'Marcelo Flores', p: 'MID', c: 'Tigres UANL' },
      { n: 'Ismaël Koné', p: 'MID', c: 'Sassuolo' },
      { n: 'Liam Millar', p: 'MID', c: 'Hull City' },
      { n: 'Jonathan Osorio', p: 'MID', c: 'Toronto FC' },
      { n: 'Nathan Saliba', p: 'MID', c: 'Anderlecht' },
      { n: 'Jacob Shaffelburg', p: 'MID', c: 'LAFC' },
      { n: 'Jonathan David', p: 'FWD', c: 'Juventus' },
      { n: 'Promise David', p: 'FWD', c: 'Union Saint-Gilloise' },
      { n: 'Cyle Larin', p: 'FWD', c: 'Southampton' },
      { n: 'Tani Oluwaseyi', p: 'FWD', c: 'Villarreal' },
    ],
  },
  'Bosnia and Herzegovina': {
    coach: 'Sergej Barbarez',
    players: [
      { n: 'Nikola Vasilj', p: 'GK', c: 'St. Pauli' },
      { n: 'Martin Zlomislić', p: 'GK', c: 'Rijeka' },
      { n: 'Osman Hadžikić', p: 'GK', c: 'Slaven Belupo' },
      { n: 'Sead Kolašinac', p: 'DEF', c: 'Atalanta' },
      { n: 'Amar Dedić', p: 'DEF', c: 'Benfica' },
      { n: 'Nihad Mujakić', p: 'DEF', c: 'Gaziantep' },
      { n: 'Nikola Katić', p: 'DEF', c: 'Schalke 04' },
      { n: 'Tarik Muharemović', p: 'DEF', c: 'Sassuolo' },
      { n: 'Stjepan Radeljić', p: 'DEF', c: 'Rijeka' },
      { n: 'Dennis Hadžikadunić', p: 'DEF', c: 'Sampdoria' },
      { n: 'Nidal Ćelik', p: 'DEF', c: 'Lens' },
      { n: 'Amir Hadžiahmetović', p: 'MID', c: 'Hull City' },
      { n: 'Ivan Šunjić', p: 'MID', c: 'Pafos' },
      { n: 'Ivan Bašić', p: 'MID', c: 'Astana' },
      { n: 'Dženis Burnić', p: 'MID', c: 'Karlsruher SC' },
      { n: 'Ermin Mahmić', p: 'MID', c: 'Slovan Liberec' },
      { n: 'Benjamin Tahirović', p: 'MID', c: 'Brøndby' },
      { n: 'Amar Memić', p: 'MID', c: 'Viktoria Plzeň' },
      { n: 'Armin Gigović', p: 'MID', c: 'Young Boys' },
      { n: 'Kerim Alajbegović', p: 'MID', c: 'RB Salzburg' },
      { n: 'Esmir Bajraktarević', p: 'MID', c: 'PSV Eindhoven' },
      { n: 'Ermedin Demirović', p: 'FWD', c: 'Stuttgart' },
      { n: 'Jovo Lukić', p: 'FWD', c: 'Universitatea Cluj' },
      { n: 'Samed Baždar', p: 'FWD', c: 'Jagiellonia Białystok' },
      { n: 'Haris Tabaković', p: 'FWD', c: 'Borussia Mönchengladbach' },
      { n: 'Edin Džeko', p: 'FWD', c: 'Schalke 04' },
    ],
  },
  'Qatar': {
    coach: 'Julen Lopetegui',
    players: [
      { n: 'Salah Zakaria', p: 'GK', c: 'Al-Duhail' },
      { n: 'Meshaal Barsham', p: 'GK', c: 'Al-Sadd' },
      { n: 'Mahmoud Abunada', p: 'GK', c: 'Al-Rayyan' },
      { n: 'Boualem Khoukhi', p: 'DEF', c: 'Al-Sadd' },
      { n: 'Pedro Miguel', p: 'DEF', c: 'Al-Sadd' },
      { n: 'Sultan Al-Brake', p: 'DEF', c: 'Al-Duhail' },
      { n: 'Al-Hashmi Al-Hussain', p: 'DEF', c: 'Al-Arabi' },
      { n: 'Ayoub Al-Alawi', p: 'DEF', c: 'Al-Gharafa' },
      { n: 'Issa Laye', p: 'DEF', c: 'Al-Arabi' },
      { n: 'Lucas Mendes', p: 'DEF', c: 'Al-Wakrah' },
      { n: 'Homam Al-Amin', p: 'DEF', c: 'Cultural Leonesa' },
      { n: 'Ahmed Fathi', p: 'MID', c: 'Al-Arabi' },
      { n: 'Jassim Gaber', p: 'MID', c: 'Al-Rayyan' },
      { n: 'Assim Madibo', p: 'MID', c: 'Al-Wakrah' },
      { n: 'Abdulaziz Hatem', p: 'MID', c: 'Al-Rayyan' },
      { n: 'Karim Boudiaf', p: 'MID', c: 'Al-Duhail' },
      { n: 'Mohammed Mannai', p: 'MID', c: 'Al-Shamal' },
      { n: 'Almoez Ali', p: 'FWD', c: 'Al-Duhail' },
      { n: 'Akram Afif', p: 'FWD', c: 'Al-Sadd' },
      { n: 'Tahsin Mohammed', p: 'FWD', c: 'Al-Duhail' },
      { n: 'Edmílson Junior', p: 'FWD', c: 'Al-Duhail' },
      { n: 'Ahmed Al-Ganehi', p: 'FWD', c: 'Al-Gharafa' },
      { n: 'Ahmed Alaa', p: 'FWD', c: 'Al-Rayyan' },
      { n: 'Hassan Al-Haydos', p: 'FWD', c: 'Al-Sadd' },
      { n: 'Mohammed Muntari', p: 'FWD', c: 'Al-Gharafa' },
      { n: 'Yusuf Abdurisag', p: 'FWD', c: 'Al-Wakrah' },
    ],
  },
  'Switzerland': {
    coach: 'Murat Yakin',
    players: [
      { n: 'Gregor Kobel', p: 'GK', c: 'Borussia Dortmund' },
      { n: 'Yvon Mvogo', p: 'GK', c: 'Lorient' },
      { n: 'Marvin Keller', p: 'GK', c: 'Young Boys' },
      { n: 'Manuel Akanji', p: 'DEF', c: 'Inter Milan' },
      { n: 'Nico Elvedi', p: 'DEF', c: "Borussia Mönchengladbach" },
      { n: 'Ricardo Rodríguez', p: 'DEF', c: 'Real Betis' },
      { n: 'Silvan Widmer', p: 'DEF', c: 'Mainz 05' },
      { n: 'Miro Muheim', p: 'DEF', c: 'Hamburger SV' },
      { n: 'Aurèle Amenda', p: 'DEF', c: 'Eintracht Frankfurt' },
      { n: 'Eray Cömert', p: 'DEF', c: 'Valencia' },
      { n: 'Luca Jaquez', p: 'DEF', c: 'Stuttgart' },
      { n: 'Granit Xhaka', p: 'MID', c: 'Sunderland' },
      { n: 'Johan Manzambi', p: 'MID', c: 'Freiburg' },
      { n: 'Remo Freuler', p: 'MID', c: 'Bologna' },
      { n: 'Denis Zakaria', p: 'MID', c: 'Monaco' },
      { n: 'Ardon Jashari', p: 'MID', c: 'AC Milan' },
      { n: 'Djibril Sow', p: 'MID', c: 'Sevilla' },
      { n: 'Christian Fassnacht', p: 'MID', c: 'Young Boys' },
      { n: 'Michel Aebischer', p: 'MID', c: 'Pisa' },
      { n: 'Fabian Rieder', p: 'MID', c: 'Augsburg' },
      { n: 'Rubén Vargas', p: 'MID', c: 'Sevilla' },
      { n: 'Breel Embolo', p: 'FWD', c: 'Rennes' },
      { n: 'Noah Okafor', p: 'FWD', c: 'Leeds United' },
      { n: 'Dan Ndoye', p: 'FWD', c: 'Nottingham Forest' },
      { n: 'Zeki Amdouni', p: 'FWD', c: 'Burnley' },
      { n: 'Cedric Itten', p: 'FWD', c: 'Fortuna Düsseldorf' },
    ],
  },

  // ---------------- GROUP C ----------------
  'Brazil': {
    coach: 'Carlo Ancelotti',
    players: [
      { n: 'Alisson', p: 'GK', c: 'Liverpool' },
      { n: 'Éderson', p: 'GK', c: 'Fenerbahçe' },
      { n: 'Weverton', p: 'GK', c: 'Grêmio' },
      { n: 'Alex Sandro', p: 'DEF', c: 'Flamengo' },
      { n: 'Bremer', p: 'DEF', c: 'Juventus' },
      { n: 'Danilo', p: 'DEF', c: 'Flamengo' },
      { n: 'Douglas Santos', p: 'DEF', c: 'Zenit' },
      { n: 'Gabriel Magalhães', p: 'DEF', c: 'Arsenal' },
      { n: 'Léo Pereira', p: 'DEF', c: 'Flamengo' },
      { n: 'Marquinhos', p: 'DEF', c: 'Paris Saint-Germain' },
      { n: 'Roger Ibañez', p: 'DEF', c: 'Al-Ahli' },
      { n: 'Wesley', p: 'DEF', c: 'Roma' },
      { n: 'Bruno Guimarães', p: 'MID', c: 'Newcastle United' },
      { n: 'Casemiro', p: 'MID', c: 'Manchester United' },
      { n: 'Danilo Santos', p: 'MID', c: 'Botafogo' },
      { n: 'Fabinho', p: 'MID', c: 'Al-Ittihad' },
      { n: 'Lucas Paquetá', p: 'MID', c: 'Flamengo' },
      { n: 'Endrick', p: 'FWD', c: 'Lyon' },
      { n: 'Gabriel Martinelli', p: 'FWD', c: 'Arsenal' },
      { n: 'Igor Thiago', p: 'FWD', c: 'Brentford' },
      { n: 'Luiz Henrique', p: 'FWD', c: 'Zenit' },
      { n: 'Matheus Cunha', p: 'FWD', c: 'Manchester United' },
      { n: 'Neymar', p: 'FWD', c: 'Santos' },
      { n: 'Raphinha', p: 'FWD', c: 'Barcelona' },
      { n: 'Rayan', p: 'FWD', c: 'Bournemouth' },
      { n: 'Vinícius Júnior', p: 'FWD', c: 'Real Madrid' },
    ],
  },
  'Morocco': {
    coach: 'Walid Regragui',
    players: [
      { n: 'Yassine Bounou', p: 'GK', c: 'Al-Hilal' },
      { n: 'Munir El Kajoui', p: 'GK', c: 'RS Berkane' },
      { n: 'Reda Tagnaouti', p: 'GK', c: 'AS FAR' },
      { n: 'Noussair Mazraoui', p: 'DEF', c: 'Manchester United' },
      { n: 'Anass Salah-Eddine', p: 'DEF', c: 'PSV Eindhoven' },
      { n: 'Youssef Belammari', p: 'DEF', c: 'Al-Ahly' },
      { n: 'Achraf Hakimi', p: 'DEF', c: 'Paris Saint-Germain' },
      { n: 'Zakaria El Ouahdi', p: 'DEF', c: 'Genk' },
      { n: 'Chadi Riad', p: 'DEF', c: 'Crystal Palace' },
      { n: 'Nayef Aguerd', p: 'DEF', c: 'Marseille' },
      { n: 'Redouane Halhal', p: 'DEF', c: 'KV Mechelen' },
      { n: 'Issa Diop', p: 'DEF', c: 'Fulham' },
      { n: 'Samir El Mourabet', p: 'MID', c: 'Strasbourg' },
      { n: 'Ayyoub Bouaddi', p: 'MID', c: 'Lille' },
      { n: 'Neil El Aynaoui', p: 'MID', c: 'Roma' },
      { n: 'Sofyan Amrabat', p: 'MID', c: 'Real Betis' },
      { n: 'Azzedine Ounahi', p: 'MID', c: 'Girona' },
      { n: 'Bilal El Khannouss', p: 'MID', c: 'Stuttgart' },
      { n: 'Ismael Saibari', p: 'MID', c: 'PSV Eindhoven' },
      { n: 'Abde Ezzalzouli', p: 'FWD', c: 'Real Betis' },
      { n: 'Chemsdine Talbi', p: 'FWD', c: 'Sunderland' },
      { n: 'Soufiane Rahimi', p: 'FWD', c: 'Al-Ain' },
      { n: 'Ayoub El Kaabi', p: 'FWD', c: 'Olympiacos' },
      { n: 'Brahim Díaz', p: 'FWD', c: 'Real Madrid' },
      { n: 'Gessime Yassine', p: 'FWD', c: 'Strasbourg' },
      { n: 'Ayoube Amaimouni', p: 'FWD', c: 'Eintracht Frankfurt' },
    ],
  },
  'Haiti': {
    coach: 'Sébastien Migné',
    players: [
      { n: 'Johny Placide', p: 'GK', c: 'Bastia' },
      { n: 'Alexandre Pierre', p: 'GK', c: 'Sochaux' },
      { n: 'Josué Duverger', p: 'GK', c: 'Cosmos Koblenz' },
      { n: 'Carlens Arcus', p: 'DEF', c: 'Angers' },
      { n: 'Wilguens Paugain', p: 'DEF', c: 'Zulte Waregem' },
      { n: 'Duke Lacroix', p: 'DEF', c: 'Colorado Springs' },
      { n: 'Martin Expérience', p: 'DEF', c: 'Nancy' },
      { n: 'Jean-Kévin Duverne', p: 'DEF', c: 'Gent' },
      { n: 'Ricardo Adé', p: 'DEF', c: 'LDU Quito' },
      { n: 'Hannes Delcroix', p: 'DEF', c: 'Lugano' },
      { n: 'Keeto Thermoncy', p: 'DEF', c: 'Young Boys' },
      { n: 'Carl Fred Sainté', p: 'MID', c: 'El Paso Locomotive' },
      { n: 'Leverton Pierre', p: 'MID', c: 'Vizela' },
      { n: 'Danley Jean Jacques', p: 'MID', c: 'Philadelphia Union' },
      { n: 'Jean-Ricner Bellegarde', p: 'MID', c: 'Wolverhampton' },
      { n: 'Woodensky Pierre', p: 'MID', c: 'Violette' },
      { n: 'Dominique Simon', p: 'MID', c: 'Tatran Prešov' },
      { n: 'Don Deedson Louicius', p: 'FWD', c: 'FC Dallas' },
      { n: 'Josué Casimir', p: 'FWD', c: 'Auxerre' },
      { n: 'Derrick Etienne', p: 'FWD', c: 'Toronto FC' },
      { n: 'Ruben Providence', p: 'FWD', c: 'Almere City' },
      { n: 'Duckens Nazon', p: 'FWD', c: 'Esteghlal' },
      { n: 'Frantzdy Pierrot', p: 'FWD', c: 'Çaykur Rizespor' },
      { n: 'Wilson Isidor', p: 'FWD', c: 'Sunderland' },
      { n: 'Yassin Fortuné', p: 'FWD', c: 'Vizela' },
      { n: 'Lenny Joseph', p: 'FWD', c: 'Ferencváros' },
    ],
  },
  'Scotland': {
    coach: 'Steve Clarke',
    players: [
      { n: 'Craig Gordon', p: 'GK', c: 'Heart of Midlothian' },
      { n: 'Angus Gunn', p: 'GK', c: 'Nottingham Forest' },
      { n: 'Liam Kelly', p: 'GK', c: 'Rangers' },
      { n: 'Grant Hanley', p: 'DEF', c: 'Hibernian' },
      { n: 'Jack Hendry', p: 'DEF', c: 'Al-Ettifaq' },
      { n: 'Aaron Hickey', p: 'DEF', c: 'Brentford' },
      { n: 'Dom Hyam', p: 'DEF', c: 'Wrexham' },
      { n: 'Scott McKenna', p: 'DEF', c: 'Dinamo Zagreb' },
      { n: 'Nathan Patterson', p: 'DEF', c: 'Everton' },
      { n: 'Anthony Ralston', p: 'DEF', c: 'Celtic' },
      { n: 'Andy Robertson', p: 'DEF', c: 'Liverpool' },
      { n: 'John Souttar', p: 'DEF', c: 'Rangers' },
      { n: 'Kieran Tierney', p: 'DEF', c: 'Celtic' },
      { n: 'Ryan Christie', p: 'MID', c: 'Bournemouth' },
      { n: 'Finlay Curtis', p: 'MID', c: 'Kilmarnock' },
      { n: 'Lewis Ferguson', p: 'MID', c: 'Bologna' },
      { n: 'Ben Gannon-Doak', p: 'MID', c: 'Bournemouth' },
      { n: 'Billy Gilmour', p: 'MID', c: 'Napoli' },
      { n: 'John McGinn', p: 'MID', c: 'Aston Villa' },
      { n: 'Kenny McLean', p: 'MID', c: 'Norwich City' },
      { n: 'Scott McTominay', p: 'MID', c: 'Napoli' },
      { n: 'Ché Adams', p: 'FWD', c: 'Torino' },
      { n: 'Lyndon Dykes', p: 'FWD', c: 'Charlton Athletic' },
      { n: 'George Hirst', p: 'FWD', c: 'Ipswich Town' },
      { n: 'Lawrence Shankland', p: 'FWD', c: 'Heart of Midlothian' },
      { n: 'Ross Stewart', p: 'FWD', c: 'Southampton' },
    ],
  },

  // ---------------- GROUP D ----------------
  'United States': {
    coach: 'Mauricio Pochettino',
    players: [
      { n: 'Chris Brady', p: 'GK', c: 'Chicago Fire' },
      { n: 'Matt Freese', p: 'GK', c: 'New York City FC' },
      { n: 'Matt Turner', p: 'GK', c: 'New England Revolution' },
      { n: 'Max Arfsten', p: 'DEF', c: 'Columbus Crew' },
      { n: 'Sergiño Dest', p: 'DEF', c: 'PSV Eindhoven' },
      { n: 'Alex Freeman', p: 'DEF', c: 'Villarreal' },
      { n: 'Mark McKenzie', p: 'DEF', c: 'Toulouse' },
      { n: 'Tim Ream', p: 'DEF', c: 'Charlotte FC' },
      { n: 'Chris Richards', p: 'DEF', c: 'Crystal Palace' },
      { n: 'Antonee Robinson', p: 'DEF', c: 'Fulham' },
      { n: 'Miles Robinson', p: 'DEF', c: 'FC Cincinnati' },
      { n: 'Joe Scally', p: 'DEF', c: 'Borussia Mönchengladbach' },
      { n: 'Auston Trusty', p: 'DEF', c: 'Celtic' },
      { n: 'Tyler Adams', p: 'MID', c: 'Bournemouth' },
      { n: 'Sebastian Berhalter', p: 'MID', c: 'Vancouver Whitecaps' },
      { n: 'Weston McKennie', p: 'MID', c: 'Juventus' },
      { n: 'Cristian Roldan', p: 'MID', c: 'Seattle Sounders' },
      { n: 'Brenden Aaronson', p: 'MID', c: 'Leeds United' },
      { n: 'Malik Tillman', p: 'MID', c: 'Bayer Leverkusen' },
      { n: 'Tim Weah', p: 'MID', c: 'Marseille' },
      { n: 'Alejandro Zendejas', p: 'MID', c: 'Club América' },
      { n: 'Christian Pulisic', p: 'FWD', c: 'AC Milan' },
      { n: 'Gio Reyna', p: 'FWD', c: 'Borussia Mönchengladbach' },
      { n: 'Folarin Balogun', p: 'FWD', c: 'Monaco' },
      { n: 'Ricardo Pepi', p: 'FWD', c: 'PSV Eindhoven' },
      { n: 'Haji Wright', p: 'FWD', c: 'Coventry City' },
    ],
  },
  'Paraguay': {
    coach: 'Gustavo Alfaro',
    players: [
      { n: 'Roberto Fernández', p: 'GK', c: 'Cerro Porteño' },
      { n: 'Orlando Gill', p: 'GK', c: 'San Lorenzo' },
      { n: 'Gastón Olveira', p: 'GK', c: 'Olimpia' },
      { n: 'Gustavo Gómez', p: 'DEF', c: 'Palmeiras' },
      { n: 'Júnior Alonso', p: 'DEF', c: 'Atlético Mineiro' },
      { n: 'Fabián Balbuena', p: 'DEF', c: 'Grêmio' },
      { n: 'Omar Alderete', p: 'DEF', c: 'Sunderland' },
      { n: 'Juan Cáceres', p: 'DEF', c: 'Dynamo Moscow' },
      { n: 'José Canale', p: 'DEF', c: 'Lanús' },
      { n: 'Alexandro Maidana', p: 'DEF', c: 'Talleres' },
      { n: 'Gustavo Velázquez', p: 'DEF', c: 'Cerro Porteño' },
      { n: 'Miguel Almirón', p: 'MID', c: 'Atlanta United' },
      { n: 'Kaku', p: 'MID', c: 'Al-Ain' },
      { n: 'Andrés Cubas', p: 'MID', c: 'Vancouver Whitecaps' },
      { n: 'Ramón Sosa', p: 'MID', c: 'Palmeiras' },
      { n: 'Diego Gómez', p: 'MID', c: 'Brighton' },
      { n: 'Damián Bobadilla', p: 'MID', c: 'São Paulo' },
      { n: 'Braian Ojeda', p: 'MID', c: 'Orlando City' },
      { n: 'Matías Galarza', p: 'MID', c: 'Atlanta United' },
      { n: 'Maurício', p: 'MID', c: 'Palmeiras' },
      { n: 'Antonio Sanabria', p: 'FWD', c: 'Cremonese' },
      { n: 'Julio Enciso', p: 'FWD', c: 'Strasbourg' },
      { n: 'Gabriel Ávalos', p: 'FWD', c: 'Independiente' },
      { n: 'Alex Arce', p: 'FWD', c: 'Independiente Rivadavia' },
      { n: 'Isidro Pitta', p: 'FWD', c: 'Red Bull Bragantino' },
      { n: 'Gustavo Caballero', p: 'FWD', c: 'Portsmouth' },
    ],
  },
  'Australia': {
    coach: 'Tony Popovic',
    players: [
      { n: 'Mathew Ryan', p: 'GK', c: 'Levante' },
      { n: 'Paul Izzo', p: 'GK', c: 'Randers' },
      { n: 'Patrick Beach', p: 'GK', c: 'Melbourne City' },
      { n: 'Jordan Bos', p: 'DEF', c: 'Feyenoord' },
      { n: 'Aziz Behich', p: 'DEF', c: 'Melbourne City' },
      { n: 'Harry Souttar', p: 'DEF', c: 'Leicester City' },
      { n: 'Alessandro Circati', p: 'DEF', c: 'Parma' },
      { n: 'Lucas Herrington', p: 'DEF', c: 'Colorado Rapids' },
      { n: 'Cameron Burgess', p: 'DEF', c: 'Swansea City' },
      { n: 'Kai Trewin', p: 'DEF', c: 'New York City FC' },
      { n: 'Milos Degenek', p: 'DEF', c: 'APOEL Nicosia' },
      { n: 'Jason Geria', p: 'DEF', c: 'Albirex Niigata' },
      { n: 'Jacob Italiano', p: 'DEF', c: 'Grazer AK' },
      { n: 'Jackson Irvine', p: 'MID', c: 'St. Pauli' },
      { n: "Aiden O'Neill", p: 'MID', c: 'New York City FC' },
      { n: 'Paul Okon Jr', p: 'MID', c: 'Sydney FC' },
      { n: 'Cameron Devlin', p: 'MID', c: 'Heart of Midlothian' },
      { n: 'Connor Metcalfe', p: 'MID', c: 'St. Pauli' },
      { n: 'Mathew Leckie', p: 'FWD', c: 'Melbourne City' },
      { n: 'Nishan Velupillay', p: 'FWD', c: 'Melbourne Victory' },
      { n: 'Cristian Volpato', p: 'FWD', c: 'Sassuolo' },
      { n: 'Nestory Irankunda', p: 'FWD', c: 'Watford' },
      { n: 'Awer Mabil', p: 'FWD', c: 'Castellón' },
      { n: 'Ajdin Hrustic', p: 'FWD', c: 'Heracles Almelo' },
      { n: 'Mohamed Toure', p: 'FWD', c: 'Norwich City' },
      { n: 'Tete Yengi', p: 'FWD', c: 'Machida Zelvia' },
    ],
  },
  'Türkiye': { coach: 'Vincenzo Montella', announced: false },

  // ---------------- GROUP E ----------------
  'Germany': {
    coach: 'Julian Nagelsmann',
    players: [
      { n: 'Oliver Baumann', p: 'GK', c: 'Hoffenheim' },
      { n: 'Manuel Neuer', p: 'GK', c: 'Bayern Munich' },
      { n: 'Alexander Nübel', p: 'GK', c: 'Stuttgart' },
      { n: 'Waldemar Anton', p: 'DEF', c: 'Borussia Dortmund' },
      { n: 'Nathaniel Brown', p: 'DEF', c: 'Eintracht Frankfurt' },
      { n: 'David Raum', p: 'DEF', c: 'RB Leipzig' },
      { n: 'Antonio Rüdiger', p: 'DEF', c: 'Real Madrid' },
      { n: 'Nico Schlotterbeck', p: 'DEF', c: 'Borussia Dortmund' },
      { n: 'Jonathan Tah', p: 'DEF', c: 'Bayern Munich' },
      { n: 'Malick Thiaw', p: 'DEF', c: 'Newcastle United' },
      { n: 'Pascal Groß', p: 'MID', c: 'Borussia Dortmund' },
      { n: 'Joshua Kimmich', p: 'MID', c: 'Bayern Munich' },
      { n: 'Felix Nmecha', p: 'MID', c: 'Borussia Dortmund' },
      { n: 'Aleksandar Pavlović', p: 'MID', c: 'Bayern Munich' },
      { n: 'Angelo Stiller', p: 'MID', c: 'Stuttgart' },
      { n: 'Leon Goretzka', p: 'MID', c: 'Bayern Munich' },
      { n: 'Florian Wirtz', p: 'MID', c: 'Liverpool' },
      { n: 'Jamie Leweling', p: 'MID', c: 'Stuttgart' },
      { n: 'Maximilian Beier', p: 'FWD', c: 'Borussia Dortmund' },
      { n: 'Kai Havertz', p: 'FWD', c: 'Arsenal' },
      { n: 'Lennart Karl', p: 'FWD', c: 'Bayern Munich' },
      { n: 'Jamal Musiala', p: 'FWD', c: 'Bayern Munich' },
      { n: 'Leroy Sané', p: 'FWD', c: 'Galatasaray' },
      { n: 'Deniz Undav', p: 'FWD', c: 'Stuttgart' },
      { n: 'Nick Woltemade', p: 'FWD', c: 'Newcastle United' },
    ],
  },
  'Curaçao': { coach: 'Dick Advocaat', announced: false },
  "Côte d'Ivoire": {
    coach: 'Emerse Faé',
    players: [
      { n: 'Yahia Fofana', p: 'GK', c: 'Rizespor' },
      { n: 'Mohamed Koné', p: 'GK', c: 'Charleroi' },
      { n: 'Alban Lafont', p: 'GK', c: 'Panathinaikos' },
      { n: 'Emmanuel Agbadou', p: 'DEF', c: 'Beşiktaş' },
      { n: 'Clément Akpa', p: 'DEF', c: 'Auxerre' },
      { n: 'Ousmane Diomandé', p: 'DEF', c: 'Sporting CP' },
      { n: 'Guéla Doué', p: 'DEF', c: 'Strasbourg' },
      { n: 'Ghislain Konan', p: 'DEF', c: 'Gil Vicente' },
      { n: 'Odilon Kossounou', p: 'DEF', c: 'Atalanta' },
      { n: 'Evan Ndicka', p: 'DEF', c: 'Roma' },
      { n: 'Wilfried Singo', p: 'DEF', c: 'Galatasaray' },
      { n: 'Seko Fofana', p: 'MID', c: 'Porto' },
      { n: 'Parfait Guiagon', p: 'MID', c: 'Charleroi' },
      { n: 'Franck Kessié', p: 'MID', c: 'Al-Ahli' },
      { n: 'Christ Inao Oulaï', p: 'MID', c: 'Trabzonspor' },
      { n: 'Ibrahim Sangaré', p: 'MID', c: 'Nottingham Forest' },
      { n: 'Jean-Michaël Seri', p: 'MID', c: 'Maribor' },
      { n: 'Simon Adingra', p: 'FWD', c: 'Monaco' },
      { n: 'Ange-Yoan Bonny', p: 'FWD', c: 'Inter Milan' },
      { n: 'Amad Diallo', p: 'FWD', c: 'Manchester United' },
      { n: 'Oumar Diakité', p: 'FWD', c: 'Cercle Brugge' },
      { n: 'Yan Diomande', p: 'FWD', c: 'RB Leipzig' },
      { n: 'Evann Guessand', p: 'FWD', c: 'Aston Villa' },
      { n: 'Nicolas Pépé', p: 'FWD', c: 'Villarreal' },
      { n: 'Bazoumana Touré', p: 'FWD', c: 'Hoffenheim' },
      { n: 'Elye Wahi', p: 'FWD', c: 'Nice' },
    ],
  },
  'Ecuador': {
    coach: 'Sebastián Beccacece',
    players: [
      { n: 'Hernán Galíndez', p: 'GK', c: 'Huracán' },
      { n: 'Moisés Ramírez', p: 'GK', c: 'AE Kifisias' },
      { n: 'Gonzalo Valle', p: 'GK', c: 'LDU Quito' },
      { n: 'Willian Pacho', p: 'DEF', c: 'Paris Saint-Germain' },
      { n: 'Piero Hincapié', p: 'DEF', c: 'Arsenal' },
      { n: 'Joel Ordóñez', p: 'DEF', c: 'Club Brugge' },
      { n: 'Félix Torres', p: 'DEF', c: 'Internacional' },
      { n: 'Pervis Estupiñán', p: 'DEF', c: 'AC Milan' },
      { n: 'Yaimar Medina', p: 'DEF', c: 'Genk' },
      { n: 'Ángelo Preciado', p: 'DEF', c: 'Atlético Mineiro' },
      { n: 'Jackson Porozo', p: 'DEF', c: 'Tijuana' },
      { n: 'Alan Minda', p: 'MID', c: 'Atlético Mineiro' },
      { n: 'Moisés Caicedo', p: 'MID', c: 'Chelsea' },
      { n: 'Jordy Alcívar', p: 'MID', c: 'Independiente del Valle' },
      { n: 'Denil Castillo', p: 'MID', c: 'Midtjylland' },
      { n: 'John Yeboah', p: 'MID', c: 'Venezia' },
      { n: 'Alan Franco', p: 'MID', c: 'Atlético Mineiro' },
      { n: 'Pedro Vite', p: 'MID', c: 'Pumas UNAM' },
      { n: 'Kendry Páez', p: 'MID', c: 'River Plate' },
      { n: 'Nilson Angulo', p: 'MID', c: 'Sunderland' },
      { n: 'Gonzalo Plata', p: 'MID', c: 'Flamengo' },
      { n: 'Kevin Rodríguez', p: 'FWD', c: 'Union Saint-Gilloise' },
      { n: 'Anthony Valencia', p: 'FWD', c: 'Antwerp' },
      { n: 'Enner Valencia', p: 'FWD', c: 'Pachuca' },
      { n: 'Jordy Caicedo', p: 'FWD', c: 'Huracán' },
      { n: 'Jeremy Arévalo', p: 'FWD', c: 'Stuttgart' },
    ],
  },

  // ---------------- GROUP F ----------------
  'Netherlands': {
    coach: 'Ronald Koeman',
    players: [
      { n: 'Mark Flekken', p: 'GK', c: 'Bayer Leverkusen' },
      { n: 'Robin Roefs', p: 'GK', c: 'Sunderland' },
      { n: 'Bart Verbruggen', p: 'GK', c: 'Brighton' },
      { n: 'Nathan Aké', p: 'DEF', c: 'Manchester City' },
      { n: 'Denzel Dumfries', p: 'DEF', c: 'Inter Milan' },
      { n: 'Jorrel Hato', p: 'DEF', c: 'Chelsea' },
      { n: 'Jurriën Timber', p: 'DEF', c: 'Arsenal' },
      { n: 'Jan Paul van Hecke', p: 'DEF', c: 'Brighton' },
      { n: 'Micky van de Ven', p: 'DEF', c: 'Tottenham Hotspur' },
      { n: 'Virgil van Dijk', p: 'DEF', c: 'Liverpool' },
      { n: 'Frenkie de Jong', p: 'MID', c: 'Barcelona' },
      { n: 'Marten de Roon', p: 'MID', c: 'Atalanta' },
      { n: 'Ryan Gravenberch', p: 'MID', c: 'Liverpool' },
      { n: 'Teun Koopmeiners', p: 'MID', c: 'Juventus' },
      { n: 'Tijjani Reijnders', p: 'MID', c: 'Manchester City' },
      { n: 'Guus Til', p: 'MID', c: 'PSV Eindhoven' },
      { n: 'Quinten Timber', p: 'MID', c: 'Marseille' },
      { n: 'Mats Wieffer', p: 'MID', c: 'Brighton' },
      { n: 'Brian Brobbey', p: 'FWD', c: 'Sunderland' },
      { n: 'Memphis Depay', p: 'FWD', c: 'Corinthians' },
      { n: 'Cody Gakpo', p: 'FWD', c: 'Liverpool' },
      { n: 'Justin Kluivert', p: 'FWD', c: 'Bournemouth' },
      { n: 'Noa Lang', p: 'FWD', c: 'Galatasaray' },
      { n: 'Donyell Malen', p: 'FWD', c: 'Roma' },
      { n: 'Crysencio Summerville', p: 'FWD', c: 'West Ham United' },
      { n: 'Wout Weghorst', p: 'FWD', c: 'Ajax' },
    ],
  },
  'Japan': {
    coach: 'Hajime Moriyasu',
    players: [
      { n: 'Zion Suzuki', p: 'GK', c: 'Parma' },
      { n: 'Keisuke Osako', p: 'GK', c: 'Sanfrecce Hiroshima' },
      { n: 'Tomoki Hayakawa', p: 'GK', c: 'Kashima Antlers' },
      { n: 'Yūto Nagatomo', p: 'DEF', c: 'FC Tokyo' },
      { n: 'Shogo Taniguchi', p: 'DEF', c: 'Sint-Truiden' },
      { n: 'Ko Itakura', p: 'DEF', c: 'Ajax' },
      { n: 'Tsuyoshi Watanabe', p: 'DEF', c: 'Feyenoord' },
      { n: 'Takehiro Tomiyasu', p: 'DEF', c: 'Ajax' },
      { n: 'Hiroki Ito', p: 'DEF', c: 'Bayern Munich' },
      { n: 'Ayumu Seko', p: 'DEF', c: 'Le Havre' },
      { n: 'Yukinari Sugawara', p: 'DEF', c: 'Werder Bremen' },
      { n: 'Junnosuke Suzuki', p: 'MID', c: 'FC Copenhagen' },
      { n: 'Wataru Endo', p: 'MID', c: 'Liverpool' },
      { n: 'Junya Ito', p: 'MID', c: 'Genk' },
      { n: 'Daichi Kamada', p: 'MID', c: 'Crystal Palace' },
      { n: 'Ritsu Doan', p: 'MID', c: 'Eintracht Frankfurt' },
      { n: 'Ao Tanaka', p: 'MID', c: 'Leeds United' },
      { n: 'Keito Nakamura', p: 'MID', c: 'Stade Reims' },
      { n: 'Kaishu Sano', p: 'MID', c: 'Mainz 05' },
      { n: 'Takefusa Kubo', p: 'MID', c: 'Real Sociedad' },
      { n: 'Yuito Suzuki', p: 'MID', c: 'Freiburg' },
      { n: 'Koki Ogawa', p: 'FWD', c: 'NEC Nijmegen' },
      { n: 'Daizen Maeda', p: 'FWD', c: 'Celtic' },
      { n: 'Ayase Ueda', p: 'FWD', c: 'Feyenoord' },
      { n: 'Kento Shiogai', p: 'FWD', c: 'Wolfsburg' },
      { n: 'Keisuke Goto', p: 'FWD', c: 'Sint-Truiden' },
    ],
  },
  'Sweden': {
    coach: 'Graham Potter',
    players: [
      { n: 'Viktor Johansson', p: 'GK', c: 'Stoke City' },
      { n: 'Kristoffer Nordfeldt', p: 'GK', c: 'AIK' },
      { n: 'Jacob Widell Zetterström', p: 'GK', c: 'Derby County' },
      { n: 'Hjalmar Ekdal', p: 'DEF', c: 'Burnley' },
      { n: 'Gabriel Gudmundsson', p: 'DEF', c: 'Leeds United' },
      { n: 'Isak Hien', p: 'DEF', c: 'Atalanta' },
      { n: 'Emil Holm', p: 'DEF', c: 'Juventus' },
      { n: 'Gustaf Lagerbielke', p: 'DEF', c: 'Braga' },
      { n: 'Victor Lindelöf', p: 'DEF', c: 'Aston Villa' },
      { n: 'Erik Smith', p: 'DEF', c: 'St. Pauli' },
      { n: 'Carl Starfelt', p: 'DEF', c: 'Celta Vigo' },
      { n: 'Elliot Stroud', p: 'DEF', c: 'Mjällby' },
      { n: 'Daniel Svensson', p: 'DEF', c: 'Borussia Dortmund' },
      { n: 'Taha Ali', p: 'MID', c: 'Malmö FF' },
      { n: 'Yasin Ayari', p: 'MID', c: 'Brighton' },
      { n: 'Lucas Bergvall', p: 'MID', c: 'Tottenham Hotspur' },
      { n: 'Jesper Karlström', p: 'MID', c: 'Udinese' },
      { n: 'Ken Sema', p: 'MID', c: 'Pafos' },
      { n: 'Mattias Svanberg', p: 'MID', c: 'Wolfsburg' },
      { n: 'Besfort Zeneli', p: 'MID', c: 'Union Saint-Gilloise' },
      { n: 'Alexander Bernhardsson', p: 'FWD', c: 'Holstein Kiel' },
      { n: 'Anthony Elanga', p: 'FWD', c: 'Newcastle United' },
      { n: 'Viktor Gyökeres', p: 'FWD', c: 'Arsenal' },
      { n: 'Alexander Isak', p: 'FWD', c: 'Liverpool' },
      { n: 'Gustaf Nilsson', p: 'FWD', c: 'Club Brugge' },
      { n: 'Benjamin Nygren', p: 'FWD', c: 'Celtic' },
    ],
  },
  'Tunisia': {
    coach: 'Sami Trabelsi',
    players: [
      { n: 'Aymen Dahmen', p: 'GK', c: 'CS Sfaxien' },
      { n: 'Sabri Ben Hessen', p: 'GK', c: 'Étoile du Sahel' },
      { n: 'Abdelmouhib Chamakh', p: 'GK', c: 'Club Africain' },
      { n: 'Montassar Talbi', p: 'DEF', c: 'Lorient' },
      { n: 'Dylan Bronn', p: 'DEF', c: 'Servette' },
      { n: 'Omar Rekik', p: 'DEF', c: 'Maribor' },
      { n: 'Yan Valery', p: 'DEF', c: 'Young Boys' },
      { n: 'Ali Abdi', p: 'DEF', c: 'Nice' },
      { n: 'Moutaz Neffati', p: 'DEF', c: 'IFK Norrköping' },
      { n: 'Raed Chikhaoui', p: 'DEF', c: 'US Monastir' },
      { n: 'Adam Arous', p: 'DEF', c: 'Kasımpaşa' },
      { n: 'Mohamed Amine Ben Hamida', p: 'DEF', c: 'Espérance' },
      { n: 'Ellyes Skhiri', p: 'MID', c: 'Eintracht Frankfurt' },
      { n: 'Hannibal Mejbri', p: 'MID', c: 'Burnley' },
      { n: 'Anis Ben Slimane', p: 'MID', c: 'Norwich City' },
      { n: 'Hadj Mahmoud', p: 'MID', c: 'Lugano' },
      { n: 'Rani Khedira', p: 'MID', c: 'Union Berlin' },
      { n: 'Mortadha Ben Ouanes', p: 'MID', c: 'Kasımpaşa' },
      { n: 'Elias Achouri', p: 'FWD', c: 'FC Copenhagen' },
      { n: 'Ismaël Gharbi', p: 'FWD', c: 'Augsburg' },
      { n: 'Elias Saad', p: 'FWD', c: 'Hannover 96' },
      { n: 'Sebastian Tounekti', p: 'FWD', c: 'Celtic' },
      { n: 'Firas Chaouat', p: 'FWD', c: 'Club Africain' },
      { n: 'Khalil Ayari', p: 'FWD', c: 'Paris Saint-Germain' },
      { n: 'Hazem Mastouri', p: 'FWD', c: 'Dynamo Makhachkala' },
      { n: 'Rayan Elloumi', p: 'FWD', c: 'Vancouver Whitecaps' },
    ],
  },

  // ---------------- GROUP G ----------------
  'Belgium': {
    coach: 'Rudi Garcia',
    players: [
      { n: 'Thibaut Courtois', p: 'GK', c: 'Real Madrid' },
      { n: 'Senne Lammens', p: 'GK', c: 'Manchester United' },
      { n: 'Mike Penders', p: 'GK', c: 'Chelsea' },
      { n: 'Timothy Castagne', p: 'DEF', c: 'Fulham' },
      { n: 'Zeno Debast', p: 'DEF', c: 'Sporting CP' },
      { n: 'Maxim De Cuyper', p: 'DEF', c: 'Brighton' },
      { n: 'Koni De Winter', p: 'DEF', c: 'AC Milan' },
      { n: 'Brandon Mechele', p: 'DEF', c: 'Club Brugge' },
      { n: 'Thomas Meunier', p: 'DEF', c: 'Lille' },
      { n: 'Nathan Ngoy', p: 'DEF', c: 'Lille' },
      { n: 'Joaquin Seys', p: 'DEF', c: 'Club Brugge' },
      { n: 'Arthur Theate', p: 'DEF', c: 'Eintracht Frankfurt' },
      { n: 'Kevin De Bruyne', p: 'MID', c: 'Napoli' },
      { n: 'Amadou Onana', p: 'MID', c: 'Aston Villa' },
      { n: 'Nicolas Raskin', p: 'MID', c: 'Rangers' },
      { n: 'Youri Tielemans', p: 'MID', c: 'Aston Villa' },
      { n: 'Hans Vanaken', p: 'MID', c: 'Club Brugge' },
      { n: 'Axel Witsel', p: 'MID', c: 'Girona' },
      { n: 'Charles De Ketelaere', p: 'FWD', c: 'Atalanta' },
      { n: 'Jérémy Doku', p: 'FWD', c: 'Manchester City' },
      { n: 'Matías Fernández-Pardo', p: 'FWD', c: 'Lille' },
      { n: 'Romelu Lukaku', p: 'FWD', c: 'Napoli' },
      { n: 'Dodi Lukebakio', p: 'FWD', c: 'Benfica' },
      { n: 'Diego Moreira', p: 'FWD', c: 'Strasbourg' },
      { n: 'Alexis Saelemaekers', p: 'FWD', c: 'AC Milan' },
      { n: 'Leandro Trossard', p: 'FWD', c: 'Arsenal' },
    ],
  },
  'Egypt': {
    coach: 'Hossam Hassan',
    players: [
      { n: 'Mohamed El Shenawy', p: 'GK', c: 'Al Ahly' },
      { n: 'Mostafa Shobeir', p: 'GK', c: 'Al Ahly' },
      { n: 'El Mahdy Soliman', p: 'GK', c: 'Zamalek' },
      { n: 'Mohamed Alaa', p: 'GK', c: 'El Gouna' },
      { n: 'Mohamed Hany', p: 'DEF', c: 'Al Ahly' },
      { n: 'Tarek Alaa', p: 'DEF', c: 'Zamalek' },
      { n: 'Hamdy Fathy', p: 'DEF', c: 'Al-Wakrah' },
      { n: 'Ramy Rabia', p: 'DEF', c: 'Al-Ain' },
      { n: 'Yasser Ibrahim', p: 'DEF', c: 'Al Ahly' },
      { n: 'Hossam Abdelmaguid', p: 'DEF', c: 'Zamalek' },
      { n: 'Mohamed Abdelmonem', p: 'DEF', c: 'Nice' },
      { n: 'Ahmed Fatouh', p: 'DEF', c: 'Zamalek' },
      { n: 'Karim Hafez', p: 'DEF', c: 'Pyramids' },
      { n: 'Marwan Attia', p: 'MID', c: 'Al Ahly' },
      { n: 'Mohanad Lasheen', p: 'MID', c: 'Pyramids' },
      { n: 'Nabil Emad', p: 'MID', c: 'Al-Najma' },
      { n: 'Mahmoud Saber', p: 'MID', c: 'Zed' },
      { n: 'Ahmed Zizo', p: 'MID', c: 'Al Ahly' },
      { n: 'Emam Ashour', p: 'MID', c: 'Al Ahly' },
      { n: 'Mostafa Ziko', p: 'MID', c: 'Pyramids' },
      { n: 'Mahmoud Trezeguet', p: 'MID', c: 'Al Ahly' },
      { n: 'Ibrahim Adel', p: 'MID', c: 'Nordsjælland' },
      { n: 'Haissem Hassan', p: 'MID', c: 'Real Oviedo' },
      { n: 'Omar Marmoush', p: 'FWD', c: 'Manchester City' },
      { n: 'Mohamed Salah', p: 'FWD', c: 'Liverpool' },
      { n: 'Hamza Abdelkarim', p: 'FWD', c: 'Barcelona Atlètic' },
    ],
  },
  'Iran': {
    coach: 'Amir Ghalenoei',
    players: [
      { n: 'Alireza Beiranvand', p: 'GK', c: 'Tractor' },
      { n: 'Hossein Hosseini', p: 'GK', c: 'Sepahan' },
      { n: 'Payam Niazmand', p: 'GK', c: 'Persepolis' },
      { n: 'Danial Eiri', p: 'DEF', c: 'Malavan' },
      { n: 'Ehsan Hajsafi', p: 'DEF', c: 'Sepahan' },
      { n: 'Saleh Hardani', p: 'DEF', c: 'Esteghlal' },
      { n: 'Hossein Kanaani', p: 'DEF', c: 'Persepolis' },
      { n: 'Shoja Khalilzadeh', p: 'DEF', c: 'Tractor' },
      { n: 'Milad Mohammadi', p: 'DEF', c: 'Persepolis' },
      { n: 'Ali Nemati', p: 'DEF', c: 'Foolad' },
      { n: 'Omid Noorafkan', p: 'DEF', c: 'Foolad' },
      { n: 'Ramin Rezaeian', p: 'DEF', c: 'Foolad' },
      { n: 'Rouzbeh Cheshmi', p: 'MID', c: 'Esteghlal' },
      { n: 'Saeid Ezatolahi', p: 'MID', c: 'Shabab Al-Ahli' },
      { n: 'Mehdi Ghaedi', p: 'MID', c: 'Al-Nasr' },
      { n: 'Saman Ghoddos', p: 'MID', c: 'Ittihad Kalba' },
      { n: 'Mohammad Ghorbani', p: 'MID', c: 'Al-Wahda' },
      { n: 'Alireza Jahanbakhsh', p: 'MID', c: 'Dender' },
      { n: 'Mohammad Mohebi', p: 'MID', c: 'Rostov' },
      { n: 'Amir Mohammad Razzaghinia', p: 'MID', c: 'Esteghlal' },
      { n: 'Mehdi Torabi', p: 'MID', c: 'Tractor' },
      { n: 'Ali Alipour', p: 'FWD', c: 'Persepolis' },
      { n: 'Amirhossein Hosseinzadeh', p: 'FWD', c: 'Tractor' },
      { n: 'Amirhossein Mahmoudi', p: 'FWD', c: 'Persepolis' },
      { n: 'Mehdi Taremi', p: 'FWD', c: 'Olympiacos' },
    ],
  },
  'New Zealand': {
    coach: 'Darren Bazeley',
    players: [
      { n: 'Max Crocombe', p: 'GK', c: 'Millwall' },
      { n: 'Alex Paulsen', p: 'GK', c: 'Lechia Gdańsk' },
      { n: 'Michael Woud', p: 'GK', c: 'Auckland FC' },
      { n: 'Tim Payne', p: 'DEF', c: 'Wellington Phoenix' },
      { n: 'Francis de Vries', p: 'DEF', c: 'Auckland FC' },
      { n: 'Tyler Bindon', p: 'DEF', c: 'Nottingham Forest' },
      { n: 'Michael Boxall', p: 'DEF', c: 'Minnesota United' },
      { n: 'Liberato Cacace', p: 'DEF', c: 'Wrexham' },
      { n: 'Nando Pijnaker', p: 'DEF', c: 'Auckland FC' },
      { n: 'Finn Surman', p: 'DEF', c: 'Portland Timbers' },
      { n: 'Callan Elliot', p: 'DEF', c: 'Auckland FC' },
      { n: 'Tommy Smith', p: 'DEF', c: 'Braintree Town' },
      { n: 'Joe Bell', p: 'MID', c: 'Viking' },
      { n: 'Matthew Garbett', p: 'MID', c: 'Peterborough United' },
      { n: 'Marko Stamenic', p: 'MID', c: 'Swansea City' },
      { n: 'Sarpreet Singh', p: 'MID', c: 'Wellington Phoenix' },
      { n: 'Alex Rufer', p: 'MID', c: 'Wellington Phoenix' },
      { n: 'Ryan Thomas', p: 'MID', c: 'PEC Zwolle' },
      { n: 'Chris Wood', p: 'FWD', c: 'Nottingham Forest' },
      { n: 'Elijah Just', p: 'FWD', c: 'Motherwell' },
      { n: 'Kosta Barbarouses', p: 'FWD', c: 'Western Sydney' },
      { n: 'Ben Waine', p: 'FWD', c: 'Port Vale' },
      { n: 'Ben Old', p: 'FWD', c: 'Saint-Étienne' },
      { n: 'Callum McCowatt', p: 'FWD', c: 'Silkeborg IF' },
      { n: 'Jesse Randall', p: 'FWD', c: 'Auckland FC' },
      { n: 'Lachlan Bayliss', p: 'FWD', c: 'Newcastle Jets' },
    ],
  },

  // ---------------- GROUP H ----------------
  'Spain': {
    coach: 'Luis de la Fuente',
    players: [
      { n: 'Unai Simón', p: 'GK', c: 'Athletic Bilbao' },
      { n: 'David Raya', p: 'GK', c: 'Arsenal' },
      { n: 'Joan García', p: 'GK', c: 'Barcelona' },
      { n: 'Marc Cucurella', p: 'DEF', c: 'Chelsea' },
      { n: 'Pau Cubarsí', p: 'DEF', c: 'Barcelona' },
      { n: 'Aymeric Laporte', p: 'DEF', c: 'Athletic Bilbao' },
      { n: 'Álex Grimaldo', p: 'DEF', c: 'Bayer Leverkusen' },
      { n: 'Pedro Porro', p: 'DEF', c: 'Tottenham Hotspur' },
      { n: 'Eric García', p: 'DEF', c: 'Barcelona' },
      { n: 'Marcos Llorente', p: 'DEF', c: 'Atlético Madrid' },
      { n: 'Marc Pubill', p: 'DEF', c: 'Atlético Madrid' },
      { n: 'Gavi', p: 'MID', c: 'Barcelona' },
      { n: 'Rodri', p: 'MID', c: 'Manchester City' },
      { n: 'Pedri', p: 'MID', c: 'Barcelona' },
      { n: 'Martín Zubimendi', p: 'MID', c: 'Arsenal' },
      { n: 'Fabián Ruiz', p: 'MID', c: 'Paris Saint-Germain' },
      { n: 'Álex Baena', p: 'MID', c: 'Atlético Madrid' },
      { n: 'Mikel Merino', p: 'MID', c: 'Arsenal' },
      { n: 'Lamine Yamal', p: 'FWD', c: 'Barcelona' },
      { n: 'Nico Williams', p: 'FWD', c: 'Athletic Bilbao' },
      { n: 'Dani Olmo', p: 'FWD', c: 'Barcelona' },
      { n: 'Ferran Torres', p: 'FWD', c: 'Barcelona' },
      { n: 'Mikel Oyarzabal', p: 'FWD', c: 'Real Sociedad' },
      { n: 'Yéremy Pino', p: 'FWD', c: 'Crystal Palace' },
      { n: 'Borja Iglesias', p: 'FWD', c: 'Celta Vigo' },
      { n: 'Víctor Muñoz', p: 'FWD', c: 'Osasuna' },
    ],
  },
  'Cabo Verde': {
    coach: 'Pedro Leitão Brito (Bubista)',
    players: [
      { n: 'Vozinha', p: 'GK', c: 'Chaves' },
      { n: 'Márcio Rosa', p: 'GK', c: 'Montana' },
      { n: 'CJ dos Santos', p: 'GK', c: 'San Diego FC' },
      { n: 'Steven Moreira', p: 'DEF', c: 'Columbus Crew' },
      { n: 'Wagner Pina', p: 'DEF', c: 'Trabzonspor' },
      { n: 'João Paulo', p: 'DEF', c: 'FCSB' },
      { n: 'Sidny Lopes Cabral', p: 'DEF', c: 'Benfica' },
      { n: 'Logan Costa', p: 'DEF', c: 'Villarreal' },
      { n: 'Pico', p: 'DEF', c: 'Shamrock Rovers' },
      { n: 'Kelvin Pires', p: 'DEF', c: 'SJK' },
      { n: 'Stopira', p: 'DEF', c: 'Torreense' },
      { n: 'Diney', p: 'DEF', c: 'Al-Bataeh' },
      { n: 'Jamiro Monteiro', p: 'MID', c: 'PEC Zwolle' },
      { n: 'Telmo Arcanjo', p: 'MID', c: 'Vitória Guimarães' },
      { n: 'Yannick Semedo', p: 'MID', c: 'Farense' },
      { n: 'Laros Duarte', p: 'MID', c: 'Puskás Akadémia' },
      { n: 'Deroy Duarte', p: 'MID', c: 'Ludogorets' },
      { n: 'Kevin Pina', p: 'MID', c: 'Krasnodar' },
      { n: 'Ryan Mendes', p: 'FWD', c: 'Iğdır' },
      { n: 'Willy Semedo', p: 'FWD', c: 'Omonia' },
      { n: 'Garry Rodrigues', p: 'FWD', c: 'Apollon Limassol' },
      { n: 'Jovane Cabral', p: 'FWD', c: 'Estrela Amadora' },
      { n: 'Nuno da Costa', p: 'FWD', c: 'İstanbul Başakşehir' },
      { n: 'Dailon Livramento', p: 'FWD', c: 'Casa Pia' },
      { n: 'Gilson Benchimol', p: 'FWD', c: 'Akron Tolyatti' },
      { n: 'Hélio Varela', p: 'FWD', c: 'Maccabi Tel Aviv' },
    ],
  },
  'Saudi Arabia': {
    coach: 'Hervé Renard',
    players: [
      { n: 'Mohammed Al-Owais', p: 'GK', c: 'Al-Ula' },
      { n: 'Nawaf Al-Aqidi', p: 'GK', c: 'Al-Nassr' },
      { n: 'Ahmed Al-Kassar', p: 'GK', c: 'Al-Qadsiah' },
      { n: 'Abdulelah Al-Amri', p: 'DEF', c: 'Al-Nassr' },
      { n: 'Hassan Tambakti', p: 'DEF', c: 'Al-Hilal' },
      { n: 'Jehad Thikri', p: 'DEF', c: 'Al-Qadsiah' },
      { n: 'Ali Lajami', p: 'DEF', c: 'Al-Hilal' },
      { n: 'Hassan Kadesh', p: 'DEF', c: 'Al-Ittihad' },
      { n: 'Saud Abdulhamid', p: 'DEF', c: 'Lens' },
      { n: 'Mohammed Abu Al-Shamat', p: 'DEF', c: 'Al-Qadsiah' },
      { n: 'Ali Majrashi', p: 'DEF', c: 'Al-Ahli' },
      { n: 'Moteb Al-Harbi', p: 'DEF', c: 'Al-Hilal' },
      { n: 'Nawaf Boushal', p: 'DEF', c: 'Al-Nassr' },
      { n: 'Sultan Al-Ghannam', p: 'DEF', c: 'Al-Nassr' },
      { n: 'Mohamed Kanno', p: 'MID', c: 'Al-Hilal' },
      { n: 'Abdullah Al-Khaibari', p: 'MID', c: 'Al-Nassr' },
      { n: 'Ziyad Al-Johani', p: 'MID', c: 'Al-Ahli' },
      { n: 'Nasser Al-Dawsari', p: 'MID', c: 'Al-Hilal' },
      { n: 'Musab Al-Juwayr', p: 'MID', c: 'Al-Qadsiah' },
      { n: 'Alaa Al-Hajji', p: 'MID', c: 'Neom' },
      { n: 'Salem Al-Dawsari', p: 'MID', c: 'Al-Hilal' },
      { n: 'Khalid Al-Ghannam', p: 'MID', c: 'Al-Ettifaq' },
      { n: 'Ayman Yahya', p: 'MID', c: 'Al-Nassr' },
      { n: 'Firas Al-Buraikan', p: 'FWD', c: 'Al-Ahli' },
      { n: 'Saleh Al-Shehri', p: 'FWD', c: 'Al-Ittihad' },
      { n: 'Abdullah Al-Hamdan', p: 'FWD', c: 'Al-Nassr' },
    ],
  },
  'Uruguay': {
    coach: 'Marcelo Bielsa',
    players: [
      { n: 'Fernando Muslera', p: 'GK', c: 'Estudiantes' },
      { n: 'Sergio Rochet', p: 'GK', c: 'Internacional' },
      { n: 'Santiago Mele', p: 'GK', c: 'Monterrey' },
      { n: 'Ronald Araújo', p: 'DEF', c: 'Barcelona' },
      { n: 'José María Giménez', p: 'DEF', c: 'Atlético Madrid' },
      { n: 'Santiago Bueno', p: 'DEF', c: 'Wolverhampton' },
      { n: 'Sebastián Cáceres', p: 'DEF', c: 'América' },
      { n: 'Mathías Olivera', p: 'DEF', c: 'Napoli' },
      { n: 'Guillermo Varela', p: 'DEF', c: 'Flamengo' },
      { n: 'Matías Viña', p: 'DEF', c: 'River Plate' },
      { n: 'Joaquín Piquerez', p: 'DEF', c: 'Palmeiras' },
      { n: 'Juan Manuel Sanabria', p: 'DEF', c: 'Real Salt Lake' },
      { n: 'Federico Valverde', p: 'MID', c: 'Real Madrid' },
      { n: 'Rodrigo Bentancur', p: 'MID', c: 'Tottenham Hotspur' },
      { n: 'Manuel Ugarte', p: 'MID', c: 'Manchester United' },
      { n: 'Emiliano Martínez', p: 'MID', c: 'Palmeiras' },
      { n: 'Rodrigo Zalazar', p: 'MID', c: 'Sporting CP' },
      { n: 'Giorgian de Arrascaeta', p: 'MID', c: 'Flamengo' },
      { n: 'Nicolás de la Cruz', p: 'MID', c: 'Flamengo' },
      { n: 'Agustín Canobbio', p: 'MID', c: 'Fluminense' },
      { n: 'Maximiliano Araújo', p: 'MID', c: 'Sporting CP' },
      { n: 'Brian Rodríguez', p: 'MID', c: 'América' },
      { n: 'Facundo Pellistri', p: 'MID', c: 'Panathinaikos' },
      { n: 'Darwin Núñez', p: 'FWD', c: 'Al-Hilal' },
      { n: 'Federico Viñas', p: 'FWD', c: 'Real Oviedo' },
      { n: 'Rodrigo Aguirre', p: 'FWD', c: 'Tigres' },
    ],
  },

  // ---------------- GROUP I ----------------
  'France': {
    coach: 'Didier Deschamps',
    players: [
      { n: 'Mike Maignan', p: 'GK', c: 'AC Milan' },
      { n: 'Robin Risser', p: 'GK', c: 'Lens' },
      { n: 'Brice Samba', p: 'GK', c: 'Rennes' },
      { n: 'Lucas Digne', p: 'DEF', c: 'Aston Villa' },
      { n: 'Malo Gusto', p: 'DEF', c: 'Chelsea' },
      { n: 'Lucas Hernández', p: 'DEF', c: 'Paris Saint-Germain' },
      { n: 'Theo Hernández', p: 'DEF', c: 'Al-Hilal' },
      { n: 'Ibrahima Konaté', p: 'DEF', c: 'Liverpool' },
      { n: 'Jules Koundé', p: 'DEF', c: 'Barcelona' },
      { n: 'Maxence Lacroix', p: 'DEF', c: 'Crystal Palace' },
      { n: 'William Saliba', p: 'DEF', c: 'Arsenal' },
      { n: 'Dayot Upamecano', p: 'DEF', c: 'Bayern Munich' },
      { n: "N'Golo Kanté", p: 'MID', c: 'Al-Ittihad' },
      { n: 'Manu Koné', p: 'MID', c: 'Roma' },
      { n: 'Adrien Rabiot', p: 'MID', c: 'AC Milan' },
      { n: 'Aurélien Tchouaméni', p: 'MID', c: 'Real Madrid' },
      { n: 'Warren Zaïre-Emery', p: 'MID', c: 'Paris Saint-Germain' },
      { n: 'Maghnes Akliouche', p: 'FWD', c: 'Monaco' },
      { n: 'Bradley Barcola', p: 'FWD', c: 'Paris Saint-Germain' },
      { n: 'Rayan Cherki', p: 'FWD', c: 'Manchester City' },
      { n: 'Ousmane Dembélé', p: 'FWD', c: 'Paris Saint-Germain' },
      { n: 'Désiré Doué', p: 'FWD', c: 'Paris Saint-Germain' },
      { n: 'Jean-Philippe Mateta', p: 'FWD', c: 'Crystal Palace' },
      { n: 'Kylian Mbappé', p: 'FWD', c: 'Real Madrid' },
      { n: 'Michael Olise', p: 'FWD', c: 'Bayern Munich' },
      { n: 'Marcus Thuram', p: 'FWD', c: 'Inter Milan' },
    ],
  },
  'Senegal': {
    coach: 'Pape Thiaw',
    players: [
      { n: 'Édouard Mendy', p: 'GK', c: 'Al-Ahli' },
      { n: 'Mory Diaw', p: 'GK', c: 'Le Havre' },
      { n: 'Yehvann Diouf', p: 'GK', c: 'Nice' },
      { n: 'Krépin Diatta', p: 'DEF', c: 'Monaco' },
      { n: 'Antoine Mendy', p: 'DEF', c: 'Nice' },
      { n: 'Kalidou Koulibaly', p: 'DEF', c: 'Al-Hilal' },
      { n: 'El Hadji Malick Diouf', p: 'DEF', c: 'West Ham United' },
      { n: 'Mamadou Sarr', p: 'DEF', c: 'Chelsea' },
      { n: 'Moussa Niakhaté', p: 'DEF', c: 'Lyon' },
      { n: 'Abdoulaye Seck', p: 'DEF', c: 'Maccabi Haifa' },
      { n: 'Ismail Jakobs', p: 'DEF', c: 'Galatasaray' },
      { n: 'Idrissa Gana Gueye', p: 'MID', c: 'Everton' },
      { n: 'Pape Gueye', p: 'MID', c: 'Villarreal' },
      { n: 'Lamine Camara', p: 'MID', c: 'Monaco' },
      { n: 'Habib Diarra', p: 'MID', c: 'Sunderland' },
      { n: 'Pathé Ciss', p: 'MID', c: 'Rayo Vallecano' },
      { n: 'Pape Matar Sarr', p: 'MID', c: 'Tottenham Hotspur' },
      { n: 'Bara Sapoko Ndiaye', p: 'MID', c: 'Bayern Munich' },
      { n: 'Sadio Mané', p: 'FWD', c: 'Al-Nassr' },
      { n: 'Ismaïla Sarr', p: 'FWD', c: 'Crystal Palace' },
      { n: 'Iliman Ndiaye', p: 'FWD', c: 'Everton' },
      { n: 'Assane Diao', p: 'FWD', c: 'Como' },
      { n: 'Ibrahim Mbaye', p: 'FWD', c: 'Paris Saint-Germain' },
      { n: 'Nicolas Jackson', p: 'FWD', c: 'Chelsea' },
      { n: 'Bamba Dieng', p: 'FWD', c: 'Lorient' },
    ],
  },
  'Iraq': { coach: 'Graham Arnold', announced: false },
  'Norway': { coach: 'Ståle Solbakken', announced: false },

  // ---------------- GROUP J ----------------
  'Argentina': { coach: 'Lionel Scaloni', announced: false },
  'Algeria': { coach: 'Vladimir Petković', announced: false },
  'Austria': { coach: 'Ralf Rangnick', announced: false },
  'Jordan': { coach: 'Jamal Sellami', announced: false },

  // ---------------- GROUP K ----------------
  'Portugal': { coach: 'Roberto Martínez', announced: false },
  'DR Congo': { coach: 'Sébastien Desabre', announced: false },
  'Uzbekistan': { coach: 'Timur Kapadze', announced: false },
  'Colombia': { coach: 'Néstor Lorenzo', announced: false },

  // ---------------- GROUP L ----------------
  'England': { coach: 'Thomas Tuchel', announced: false },
  'Croatia': { coach: 'Zlatko Dalić', announced: false },
  'Ghana': { coach: 'Otto Addo', announced: false },
  'Panama': { coach: 'Thomas Christiansen', announced: false },
};
