// FIFA World Cup 2026 — provisional 26-man squads.
// Squads are illustrative provisional lists built from each nation's established
// recent internationals (2024–25 call-ups). Final 26-man lists are confirmed by
// FIFA's squad-registration deadline in early June 2026.
// p = position: GK | DEF | MID | FWD ; c = club at time of selection.

export const squads = {
  // ---------------- GROUP A ----------------
  'Mexico': {
    coach: 'Javier Aguirre',
    players: [
      { n: 'Carlos Acevedo', p: 'GK', c: 'Santos Laguna' },
      { n: 'Guillermo Ochoa', p: 'GK', c: 'AEL Limassol' },
      { n: 'Raúl Rangel', p: 'GK', c: 'Guadalajara' },
      { n: 'Jesús Gallardo', p: 'DEF', c: 'Toluca' },
      { n: 'Israel Reyes', p: 'DEF', c: 'Club América' },
      { n: 'César Montes', p: 'DEF', c: 'Lokomotiv Moscow' },
      { n: 'Jorge Sánchez', p: 'DEF', c: 'PAOK' },
      { n: 'Johan Vásquez', p: 'DEF', c: 'Genoa' },
      { n: 'Mateo Chávez', p: 'DEF', c: 'AZ Alkmaar' },
      { n: 'Gilberto Mora', p: 'MID', c: 'Tijuana' },
      { n: 'Edson Álvarez', p: 'MID', c: 'Fenerbahçe' },
      { n: 'Orbelín Pineda', p: 'MID', c: 'AEK Athens' },
      { n: 'Luis Romo', p: 'MID', c: 'Guadalajara' },
      { n: 'Brian Gutiérrez', p: 'MID', c: 'Guadalajara' },
      { n: 'Obed Vargas', p: 'MID', c: 'Atlético Madrid' },
      { n: 'César Huerta', p: 'MID', c: 'Anderlecht' },
      { n: 'Luis Chávez', p: 'MID', c: 'Dynamo Moscow' },
      { n: 'Erik Lira', p: 'MID', c: 'Cruz Azul' },
      { n: 'Álvaro Fidalgo', p: 'MID', c: 'Real Betis' },
      { n: 'Roberto Alvarado', p: 'MID', c: 'Guadalajara' },
      { n: 'Armando González', p: 'FWD', c: 'Guadalajara' },
      { n: 'Raúl Jiménez', p: 'FWD', c: 'Fulham' },
      { n: 'Julián Quiñones', p: 'FWD', c: 'Al-Qadsiah' },
      { n: 'Santiago Giménez', p: 'FWD', c: 'AC Milan' },
      { n: 'Guillermo Martínez', p: 'FWD', c: 'Pumas UNAM' },
      { n: 'Alexis Vega', p: 'FWD', c: 'Toluca' },
    ],
  },
  'South Africa': {
    coach: 'Hugo Broos',
    players: [
      { n: 'Ronwen Williams', p: 'GK', c: 'Mamelodi Sundowns' },
      { n: 'Ricardo Goss', p: 'GK', c: 'Sekhukhune United' },
      { n: 'Sipho Chaine', p: 'GK', c: 'Orlando Pirates' },
      { n: 'Nyiko Mobbie', p: 'DEF', c: 'Mamelodi Sundowns' },
      { n: 'Khuliso Mudau', p: 'DEF', c: 'Mamelodi Sundowns' },
      { n: 'Mothobi Mvala', p: 'DEF', c: 'Mamelodi Sundowns' },
      { n: 'Grant Kekana', p: 'DEF', c: 'Mamelodi Sundowns' },
      { n: 'Siyanda Xulu', p: 'DEF', c: 'Sekhukhune United' },
      { n: 'Aubrey Modiba', p: 'DEF', c: 'Mamelodi Sundowns' },
      { n: 'Nkosinathi Sibisi', p: 'DEF', c: 'Orlando Pirates' },
      { n: 'Teboho Mokoena', p: 'MID', c: 'Mamelodi Sundowns' },
      { n: 'Sphephelo Sithole', p: 'MID', c: 'Tondela' },
      { n: 'Bongani Zungu', p: 'MID', c: 'Mamelodi Sundowns' },
      { n: 'Themba Zwane', p: 'MID', c: 'Mamelodi Sundowns' },
      { n: 'Thapelo Maseko', p: 'MID', c: 'Mamelodi Sundowns' },
      { n: 'Patrick Maswanganyi', p: 'MID', c: 'Orlando Pirates' },
      { n: 'Sphelele Mkhulise', p: 'MID', c: 'Mamelodi Sundowns' },
      { n: 'Percy Tau', p: 'FWD', c: 'Qatar SC' },
      { n: 'Cassius Mailula', p: 'FWD', c: 'Mamelodi Sundowns' },
      { n: 'Lyle Foster', p: 'FWD', c: 'Burnley' },
      { n: 'Evidence Makgopa', p: 'FWD', c: 'Orlando Pirates' },
      { n: 'Mihlali Mayambela', p: 'FWD', c: 'Aris Limassol' },
      { n: 'Iqraam Rayners', p: 'FWD', c: 'Mamelodi Sundowns' },
      { n: 'Oswin Appollis', p: 'FWD', c: 'Polokwane City' },
      { n: 'Elias Mokwana', p: 'FWD', c: 'Espérance' },
      { n: 'Zakhele Lepasa', p: 'FWD', c: 'Orlando Pirates' },
    ],
  },
  'Korea Republic': {
    coach: 'Hong Myung-bo',
    players: [
      { n: 'Jo Hyun-woo', p: 'GK', c: 'Ulsan HD' },
      { n: 'Kim Seung-gyu', p: 'GK', c: 'FC Tokyo' },
      { n: 'Song Bum-keun', p: 'GK', c: 'Jeonbuk Hyundai' },
      { n: 'Kim Min-jae', p: 'DEF', c: 'Bayern Munich' },
      { n: 'Jo Yu-min', p: 'DEF', c: 'Sharjah' },
      { n: 'Lee Han-beom', p: 'DEF', c: 'Midtjylland' },
      { n: 'Kim Tae-hyun', p: 'DEF', c: 'Kashima Antlers' },
      { n: 'Park Jin-seop', p: 'DEF', c: 'Zhejiang FC' },
      { n: 'Lee Ki-hyeok', p: 'DEF', c: 'Gangwon FC' },
      { n: 'Lee Tae-seok', p: 'DEF', c: 'Austria Vienna' },
      { n: 'Seol Young-woo', p: 'DEF', c: 'Red Star Belgrade' },
      { n: 'Jens Castrop', p: 'DEF', c: 'Borussia Mönchengladbach' },
      { n: 'Kim Moon-hwan', p: 'DEF', c: 'Daejeon Hana Citizen' },
      { n: 'Yang Hyun-jun', p: 'MID', c: 'Celtic' },
      { n: 'Paik Seung-ho', p: 'MID', c: 'Birmingham City' },
      { n: 'Hwang In-beom', p: 'MID', c: 'Feyenoord' },
      { n: 'Kim Jin-kyu', p: 'MID', c: 'Jeonbuk Hyundai' },
      { n: 'Bae Jun-ho', p: 'MID', c: 'Stoke City' },
      { n: 'Um Ji-sung', p: 'MID', c: 'Swansea City' },
      { n: 'Hwang Hee-chan', p: 'MID', c: 'Wolverhampton' },
      { n: 'Lee Dong-gyeong', p: 'MID', c: 'Ulsan HD' },
      { n: 'Lee Jae-sung', p: 'MID', c: 'Mainz 05' },
      { n: 'Lee Kang-in', p: 'MID', c: 'Paris Saint-Germain' },
      { n: 'Oh Hyeon-gyu', p: 'FWD', c: 'Beşiktaş' },
      { n: 'Son Heung-min', p: 'FWD', c: 'LAFC' },
      { n: 'Cho Gue-sung', p: 'FWD', c: 'Midtjylland' },
    ],
  },
  'Czechia': {
    coach: 'Miroslav Koubek',
    players: [
      { n: 'Jindřich Staněk', p: 'GK', c: 'Slavia Prague' },
      { n: 'Matěj Kovář', p: 'GK', c: 'Bayer Leverkusen' },
      { n: 'Vítězslav Jaroš', p: 'GK', c: 'Ajax' },
      { n: 'Vladimír Coufal', p: 'DEF', c: 'West Ham United' },
      { n: 'Tomáš Holeš', p: 'DEF', c: 'Slavia Prague' },
      { n: 'Robin Hranáč', p: 'DEF', c: 'Hoffenheim' },
      { n: 'David Zima', p: 'DEF', c: 'Slavia Prague' },
      { n: 'Ladislav Krejčí', p: 'DEF', c: 'Girona' },
      { n: 'David Doudera', p: 'DEF', c: 'Slavia Prague' },
      { n: 'Martin Vitík', p: 'DEF', c: 'Sparta Prague' },
      { n: 'Tomáš Souček', p: 'MID', c: 'West Ham United' },
      { n: 'Lukáš Provod', p: 'MID', c: 'Slavia Prague' },
      { n: 'Pavel Šulc', p: 'MID', c: 'Viktoria Plzeň' },
      { n: 'Antonín Barák', p: 'MID', c: 'Fiorentina' },
      { n: 'Michal Sadílek', p: 'MID', c: 'Twente' },
      { n: 'Ondřej Lingr', p: 'MID', c: 'Feyenoord' },
      { n: 'Lukáš Červ', p: 'MID', c: 'Viktoria Plzeň' },
      { n: 'Vasil Kušej', p: 'MID', c: 'Slavia Prague' },
      { n: 'Adam Hložek', p: 'FWD', c: 'Hoffenheim' },
      { n: 'Patrik Schick', p: 'FWD', c: 'Bayer Leverkusen' },
      { n: 'Mojmír Chytil', p: 'FWD', c: 'Slavia Prague' },
      { n: 'Tomáš Chorý', p: 'FWD', c: 'Viktoria Plzeň' },
      { n: 'Václav Černý', p: 'FWD', c: 'Wolfsburg' },
      { n: 'Jan Kuchta', p: 'FWD', c: 'Sparta Prague' },
      { n: 'Matěj Vydra', p: 'FWD', c: 'Viktoria Plzeň' },
      { n: 'Daniel Vašulín', p: 'FWD', c: 'Hradec Králové' },
    ],
  },
  // ---------------- GROUP C ----------------
  'Brazil': {
    coach: 'Carlo Ancelotti',
    players: [
      { n: 'Alisson', p: 'GK', c: 'Liverpool' },
      { n: 'Ederson', p: 'GK', c: 'Manchester City' },
      { n: 'Bento', p: 'GK', c: 'Al-Nassr' },
      { n: 'Danilo', p: 'DEF', c: 'Flamengo' },
      { n: 'Marquinhos', p: 'DEF', c: 'Paris Saint-Germain' },
      { n: 'Gabriel Magalhães', p: 'DEF', c: 'Arsenal' },
      { n: 'Éder Militão', p: 'DEF', c: 'Real Madrid' },
      { n: 'Wesley', p: 'DEF', c: 'Roma' },
      { n: 'Vanderson', p: 'DEF', c: 'Monaco' },
      { n: 'Alex Sandro', p: 'DEF', c: 'Flamengo' },
      { n: 'Carlos Augusto', p: 'DEF', c: 'Inter Milan' },
      { n: 'Bruno Guimarães', p: 'MID', c: 'Newcastle United' },
      { n: 'Casemiro', p: 'MID', c: 'Manchester United' },
      { n: 'André', p: 'MID', c: 'Wolverhampton' },
      { n: 'Joelinton', p: 'MID', c: 'Newcastle United' },
      { n: 'Gerson', p: 'MID', c: 'Zenit' },
      { n: 'Lucas Paquetá', p: 'MID', c: 'West Ham United' },
      { n: 'Vinícius Júnior', p: 'FWD', c: 'Real Madrid' },
      { n: 'Rodrygo', p: 'FWD', c: 'Real Madrid' },
      { n: 'Raphinha', p: 'FWD', c: 'Barcelona' },
      { n: 'Estêvão', p: 'FWD', c: 'Chelsea' },
      { n: 'Matheus Cunha', p: 'FWD', c: 'Manchester United' },
      { n: 'Gabriel Martinelli', p: 'FWD', c: 'Arsenal' },
      { n: 'Richarlison', p: 'FWD', c: 'Tottenham Hotspur' },
      { n: 'João Pedro', p: 'FWD', c: 'Chelsea' },
      { n: 'Endrick', p: 'FWD', c: 'Real Madrid' },
    ],
  },
  'Morocco': {
    coach: 'Walid Regragui',
    players: [
      { n: 'Yassine Bounou', p: 'GK', c: 'Al-Hilal' },
      { n: 'Munir Mohamedi', p: 'GK', c: 'Al-Wehda' },
      { n: 'El Mehdi Benabid', p: 'GK', c: 'Raja Casablanca' },
      { n: 'Achraf Hakimi', p: 'DEF', c: 'Paris Saint-Germain' },
      { n: 'Noussair Mazraoui', p: 'DEF', c: 'Manchester United' },
      { n: 'Nayef Aguerd', p: 'DEF', c: 'Real Sociedad' },
      { n: 'Romain Saïss', p: 'DEF', c: 'Al-Shabab' },
      { n: 'Achraf Dari', p: 'DEF', c: 'Brest' },
      { n: 'Jawad El Yamiq', p: 'DEF', c: 'Valladolid' },
      { n: 'Adam Masina', p: 'DEF', c: 'Torino' },
      { n: 'Sofyan Amrabat', p: 'MID', c: 'Fiorentina' },
      { n: 'Azzedine Ounahi', p: 'MID', c: 'Panathinaikos' },
      { n: 'Bilal El Khannouss', p: 'MID', c: 'Stuttgart' },
      { n: 'Ismael Saibari', p: 'MID', c: 'PSV Eindhoven' },
      { n: 'Eliesse Ben Seghir', p: 'MID', c: 'Bayer Leverkusen' },
      { n: 'Neil El Aynaoui', p: 'MID', c: 'Roma' },
      { n: 'Hakim Ziyech', p: 'MID', c: 'Al-Duhail' },
      { n: 'Brahim Díaz', p: 'FWD', c: 'Real Madrid' },
      { n: 'Amine Adli', p: 'FWD', c: 'Bayer Leverkusen' },
      { n: 'Sofiane Boufal', p: 'FWD', c: 'Al-Rayyan' },
      { n: 'Youssef En-Nesyri', p: 'FWD', c: 'Fenerbahçe' },
      { n: 'Ayoub El Kaabi', p: 'FWD', c: 'Olympiacos' },
      { n: 'Soufiane Rahimi', p: 'FWD', c: 'Al-Ain' },
      { n: 'Abde Ezzalzouli', p: 'FWD', c: 'Real Betis' },
      { n: 'Chemsdine Talbi', p: 'FWD', c: 'Sunderland' },
      { n: 'Hamza Igamane', p: 'FWD', c: 'Lille' },
    ],
  },
  'Haiti': {
    coach: 'Sébastien Migné',
    players: [
      { n: 'Johny Placide', p: 'GK', c: 'Free agent' },
      { n: 'Josué Duverger', p: 'GK', c: 'Quevilly-Rouen' },
      { n: 'Alexandre Pierre', p: 'GK', c: 'Cavalry FC' },
      { n: 'Carlens Arcus', p: 'DEF', c: 'Auxerre' },
      { n: 'Ricardo Adé', p: 'DEF', c: 'Al-Markhiya' },
      { n: 'Andrew Jean-Baptiste', p: 'DEF', c: 'Real Salt Lake' },
      { n: 'Garven Metusala', p: 'DEF', c: 'Wisła Płock' },
      { n: 'Jean-Kévin Duverne', p: 'DEF', c: 'Le Havre' },
      { n: 'Christopher Attys', p: 'DEF', c: 'Bastia' },
      { n: 'Zachary Herivaux', p: 'MID', c: 'Inter Miami' },
      { n: 'Danley Jean Jacques', p: 'MID', c: 'Lorient' },
      { n: 'Jean Ricner Bellegarde', p: 'MID', c: 'Wolverhampton' },
      { n: 'Carl Sainté', p: 'MID', c: 'RWD Molenbeek' },
      { n: 'Leverton Pierre', p: 'MID', c: 'Cibao FC' },
      { n: 'Derrick Etienne', p: 'MID', c: 'Columbus Crew' },
      { n: 'Fafà Picault', p: 'FWD', c: 'Houston Dynamo' },
      { n: 'Frantzdy Pierrot', p: 'FWD', c: 'Gaziantep' },
      { n: 'Duckens Nazon', p: 'FWD', c: 'Al-Batin' },
      { n: 'Don Deedson Louicius', p: 'FWD', c: 'Lommel' },
      { n: 'Ruben Providence', p: 'FWD', c: 'Sint-Truiden' },
      { n: 'Roberto Lopes', p: 'DEF', c: 'Shamrock Rovers' },
      { n: 'Steeven Saba', p: 'MID', c: 'Aubagne' },
      { n: 'Wilde-Donald Guerrier', p: 'DEF', c: 'Free agent' },
      { n: 'Mondy Prunier', p: 'DEF', c: 'Sochaux' },
      { n: 'Jems Geffrard', p: 'DEF', c: 'Sigma Olomouc' },
      { n: 'Bryan Alceus', p: 'MID', c: 'Annecy' },
    ],
  },
  'Scotland': {
    coach: 'Steve Clarke',
    players: [
      { n: 'Angus Gunn', p: 'GK', c: 'Norwich City' },
      { n: 'Craig Gordon', p: 'GK', c: 'Heart of Midlothian' },
      { n: 'Cieran Slicker', p: 'GK', c: 'Ipswich Town' },
      { n: 'Andrew Robertson', p: 'DEF', c: 'Liverpool' },
      { n: 'Kieran Tierney', p: 'DEF', c: 'Celtic' },
      { n: 'Jack Hendry', p: 'DEF', c: 'Al-Ettifaq' },
      { n: 'Grant Hanley', p: 'DEF', c: 'Birmingham City' },
      { n: 'Ryan Porteous', p: 'DEF', c: 'Watford' },
      { n: 'Scott McKenna', p: 'DEF', c: 'Las Palmas' },
      { n: 'Anthony Ralston', p: 'DEF', c: 'Celtic' },
      { n: 'Max Johnston', p: 'DEF', c: 'Sturm Graz' },
      { n: 'Callum McGregor', p: 'MID', c: 'Celtic' },
      { n: 'Billy Gilmour', p: 'MID', c: 'Napoli' },
      { n: 'Scott McTominay', p: 'MID', c: 'Napoli' },
      { n: 'John McGinn', p: 'MID', c: 'Aston Villa' },
      { n: 'Ryan Christie', p: 'MID', c: 'Bournemouth' },
      { n: 'Lewis Ferguson', p: 'MID', c: 'Bologna' },
      { n: 'Kenny McLean', p: 'MID', c: 'Norwich City' },
      { n: 'Ben Doak', p: 'FWD', c: 'Bournemouth' },
      { n: 'Che Adams', p: 'FWD', c: 'Torino' },
      { n: 'Lyndon Dykes', p: 'FWD', c: 'Birmingham City' },
      { n: 'Lawrence Shankland', p: 'FWD', c: 'Heart of Midlothian' },
      { n: 'George Hirst', p: 'FWD', c: 'Ipswich Town' },
      { n: 'Tommy Conway', p: 'FWD', c: 'Middlesbrough' },
      { n: 'James Wilson', p: 'FWD', c: 'Heart of Midlothian' },
      { n: 'John Souttar', p: 'DEF', c: 'Rangers' },
    ],
  },
  // ---------------- GROUP D ----------------
  'United States': {
    coach: 'Mauricio Pochettino',
    players: [
      { n: 'Matt Turner', p: 'GK', c: 'New England Revolution' },
      { n: 'Patrick Schulte', p: 'GK', c: 'Columbus Crew' },
      { n: 'Zack Steffen', p: 'GK', c: 'Colorado Rapids' },
      { n: 'Sergiño Dest', p: 'DEF', c: 'PSV Eindhoven' },
      { n: 'Antonee Robinson', p: 'DEF', c: 'Fulham' },
      { n: 'Chris Richards', p: 'DEF', c: 'Crystal Palace' },
      { n: 'Tim Ream', p: 'DEF', c: 'Charlotte FC' },
      { n: 'Joe Scally', p: 'DEF', c: "Borussia Mönchengladbach" },
      { n: 'Mark McKenzie', p: 'DEF', c: 'Toulouse' },
      { n: 'Miles Robinson', p: 'DEF', c: 'FC Cincinnati' },
      { n: 'Tyler Adams', p: 'MID', c: 'Bournemouth' },
      { n: 'Weston McKennie', p: 'MID', c: 'Juventus' },
      { n: 'Yunus Musah', p: 'MID', c: 'AC Milan' },
      { n: 'Tanner Tessmann', p: 'MID', c: 'Lyon' },
      { n: 'Johnny Cardoso', p: 'MID', c: 'Atlético Madrid' },
      { n: 'Luca de la Torre', p: 'MID', c: 'San Diego FC' },
      { n: 'Christian Pulisic', p: 'FWD', c: 'AC Milan' },
      { n: 'Timothy Weah', p: 'FWD', c: 'Marseille' },
      { n: 'Gio Reyna', p: 'MID', c: 'Borussia Dortmund' },
      { n: 'Brenden Aaronson', p: 'MID', c: 'Leeds United' },
      { n: 'Folarin Balogun', p: 'FWD', c: 'Monaco' },
      { n: 'Ricardo Pepi', p: 'FWD', c: 'PSV Eindhoven' },
      { n: 'Josh Sargent', p: 'FWD', c: 'Norwich City' },
      { n: 'Haji Wright', p: 'FWD', c: 'Coventry City' },
      { n: 'Malik Tillman', p: 'MID', c: 'Bayer Leverkusen' },
      { n: 'Diego Luna', p: 'MID', c: 'Real Salt Lake' },
    ],
  },
  'Paraguay': {
    coach: 'Gustavo Alfaro',
    players: [
      { n: 'Roberto Fernández', p: 'GK', c: 'Vélez Sarsfield' },
      { n: 'Carlos Coronel', p: 'GK', c: 'New York Red Bulls' },
      { n: 'Orlando Gill', p: 'GK', c: 'Cerro Porteño' },
      { n: 'Gustavo Gómez', p: 'DEF', c: 'Palmeiras' },
      { n: 'Omar Alderete', p: 'DEF', c: 'Sunderland' },
      { n: 'Júnior Alonso', p: 'DEF', c: 'Krasnodar' },
      { n: 'Fabián Balbuena', p: 'DEF', c: 'Corinthians' },
      { n: 'Agustín Sández', p: 'DEF', c: 'Boca Juniors' },
      { n: 'Juan Cáceres', p: 'DEF', c: 'Argentinos Juniors' },
      { n: 'Alfonso Bareiro', p: 'DEF', c: 'Libertad' },
      { n: 'Andrés Cubas', p: 'MID', c: 'Vancouver Whitecaps' },
      { n: 'Mathías Villasanti', p: 'MID', c: 'Grêmio' },
      { n: 'Damián Bobadilla', p: 'MID', c: 'São Paulo' },
      { n: 'Diego Gómez', p: 'MID', c: 'Brighton' },
      { n: 'Ramón Sosa', p: 'FWD', c: 'Nottingham Forest' },
      { n: 'Miguel Almirón', p: 'MID', c: 'Atlanta United' },
      { n: 'Julio Enciso', p: 'FWD', c: 'Ipswich Town' },
      { n: 'Matías Galarza', p: 'MID', c: 'Talleres' },
      { n: 'Antonio Sanabria', p: 'FWD', c: 'Cremonese' },
      { n: 'Adam Bareiro', p: 'FWD', c: 'River Plate' },
      { n: 'Gabriel Ávalos', p: 'FWD', c: 'Racing Club' },
      { n: 'Alex Arce', p: 'FWD', c: 'LDU Quito' },
      { n: 'Ángel Romero', p: 'FWD', c: 'Corinthians' },
      { n: 'Braian Ojeda', p: 'MID', c: 'Real Salt Lake' },
      { n: 'Richard Sánchez', p: 'MID', c: 'América' },
      { n: 'Blas Riveros', p: 'DEF', c: 'Libertad' },
    ],
  },
  'Australia': {
    coach: 'Tony Popovic',
    players: [
      { n: 'Mathew Ryan', p: 'GK', c: 'Lens' },
      { n: 'Joe Gauci', p: 'GK', c: 'Aston Villa' },
      { n: 'Paul Izzo', p: 'GK', c: 'Randers' },
      { n: 'Harry Souttar', p: 'DEF', c: 'Sheffield United' },
      { n: 'Kye Rowles', p: 'DEF', c: 'Heart of Midlothian' },
      { n: 'Cameron Burgess', p: 'DEF', c: 'Ipswich Town' },
      { n: 'Aziz Behich', p: 'DEF', c: 'Melbourne City' },
      { n: 'Jordan Bos', p: 'DEF', c: 'Westerlo' },
      { n: 'Lewis Miller', p: 'DEF', c: 'Hibernian' },
      { n: 'Milos Degenek', p: 'DEF', c: 'Red Star Belgrade' },
      { n: 'Jason Geria', p: 'DEF', c: 'Melbourne Victory' },
      { n: 'Aiden O\'Neill', p: 'MID', c: 'Standard Liège' },
      { n: 'Connor Metcalfe', p: 'MID', c: 'St. Pauli' },
      { n: 'Jackson Irvine', p: 'MID', c: 'St. Pauli' },
      { n: 'Riley McGree', p: 'MID', c: 'Middlesbrough' },
      { n: 'Ajdin Hrustic', p: 'MID', c: 'Sint-Truiden' },
      { n: 'Keanu Baccus', p: 'MID', c: 'St. Mirren' },
      { n: 'Martin Boyle', p: 'FWD', c: 'Hibernian' },
      { n: 'Craig Goodwin', p: 'FWD', c: 'Al-Wehda' },
      { n: 'Mathew Leckie', p: 'FWD', c: 'Melbourne City' },
      { n: 'Kusini Yengi', p: 'FWD', c: 'Portsmouth' },
      { n: 'Nestory Irankunda', p: 'FWD', c: 'Bayern Munich' },
      { n: 'Adam Taggart', p: 'FWD', c: 'Perth Glory' },
      { n: 'Brandon Borrello', p: 'FWD', c: 'Western Sydney' },
      { n: 'Mohamed Toure', p: 'FWD', c: 'Randers' },
      { n: 'Cameron Devlin', p: 'MID', c: 'Heart of Midlothian' },
    ],
  },
  'Türkiye': {
    coach: 'Vincenzo Montella',
    players: [
      { n: 'Uğurcan Çakır', p: 'GK', c: 'Galatasaray' },
      { n: 'Altay Bayındır', p: 'GK', c: 'Manchester United' },
      { n: 'Mert Günok', p: 'GK', c: 'Beşiktaş' },
      { n: 'Zeki Çelik', p: 'DEF', c: 'Roma' },
      { n: 'Merih Demiral', p: 'DEF', c: 'Al-Ahli' },
      { n: 'Abdülkerim Bardakcı', p: 'DEF', c: 'Galatasaray' },
      { n: 'Samet Akaydın', p: 'DEF', c: 'Panathinaikos' },
      { n: 'Ferdi Kadıoğlu', p: 'DEF', c: 'Brighton' },
      { n: 'Mert Müldür', p: 'DEF', c: 'Fenerbahçe' },
      { n: 'Kaan Ayhan', p: 'DEF', c: 'Galatasaray' },
      { n: 'Hakan Çalhanoğlu', p: 'MID', c: 'Inter Milan' },
      { n: 'İsmail Yüksek', p: 'MID', c: 'Fenerbahçe' },
      { n: 'Salih Özcan', p: 'MID', c: 'Borussia Dortmund' },
      { n: 'Orkun Kökçü', p: 'MID', c: 'Benfica' },
      { n: 'Arda Güler', p: 'MID', c: 'Real Madrid' },
      { n: 'Atakan Karazor', p: 'MID', c: 'Stuttgart' },
      { n: 'İrfan Can Kahveci', p: 'MID', c: 'Fenerbahçe' },
      { n: 'Kenan Yıldız', p: 'FWD', c: 'Juventus' },
      { n: 'Kerem Aktürkoğlu', p: 'FWD', c: 'Fenerbahçe' },
      { n: 'Yusuf Yazıcı', p: 'MID', c: 'Beşiktaş' },
      { n: 'Barış Alper Yılmaz', p: 'FWD', c: 'Galatasaray' },
      { n: 'Cenk Tosun', p: 'FWD', c: 'Beşiktaş' },
      { n: 'Semih Kılıçsoy', p: 'FWD', c: 'Beşiktaş' },
      { n: 'Yunus Akgün', p: 'FWD', c: 'Galatasaray' },
      { n: 'Can Uzun', p: 'FWD', c: 'Eintracht Frankfurt' },
      { n: 'Oğuz Aydın', p: 'FWD', c: 'Fenerbahçe' },
    ],
  },
  // ---------------- GROUP E ----------------
  'Germany': {
    coach: 'Julian Nagelsmann',
    players: [
      { n: 'Marc-André ter Stegen', p: 'GK', c: 'Barcelona' },
      { n: 'Oliver Baumann', p: 'GK', c: 'Hoffenheim' },
      { n: 'Alexander Nübel', p: 'GK', c: 'Stuttgart' },
      { n: 'Joshua Kimmich', p: 'DEF', c: 'Bayern Munich' },
      { n: 'Antonio Rüdiger', p: 'DEF', c: 'Real Madrid' },
      { n: 'Jonathan Tah', p: 'DEF', c: 'Bayern Munich' },
      { n: 'Nico Schlotterbeck', p: 'DEF', c: 'Borussia Dortmund' },
      { n: 'David Raum', p: 'DEF', c: 'RB Leipzig' },
      { n: 'Maximilian Mittelstädt', p: 'DEF', c: 'Stuttgart' },
      { n: 'Waldemar Anton', p: 'DEF', c: 'Borussia Dortmund' },
      { n: 'Robin Koch', p: 'DEF', c: 'Eintracht Frankfurt' },
      { n: 'Robert Andrich', p: 'MID', c: 'Bayer Leverkusen' },
      { n: 'Pascal Groß', p: 'MID', c: 'Borussia Dortmund' },
      { n: 'Angelo Stiller', p: 'MID', c: 'Stuttgart' },
      { n: 'Aleksandar Pavlović', p: 'MID', c: 'Bayern Munich' },
      { n: 'Leon Goretzka', p: 'MID', c: 'Bayern Munich' },
      { n: 'Florian Wirtz', p: 'MID', c: 'Liverpool' },
      { n: 'Jamal Musiala', p: 'MID', c: 'Bayern Munich' },
      { n: 'Leroy Sané', p: 'FWD', c: 'Galatasaray' },
      { n: 'Serge Gnabry', p: 'FWD', c: 'Bayern Munich' },
      { n: 'Karim Adeyemi', p: 'FWD', c: 'Borussia Dortmund' },
      { n: 'Nick Woltemade', p: 'FWD', c: 'Newcastle United' },
      { n: 'Niclas Füllkrug', p: 'FWD', c: 'West Ham United' },
      { n: 'Deniz Undav', p: 'FWD', c: 'Stuttgart' },
      { n: 'Kai Havertz', p: 'FWD', c: 'Arsenal' },
      { n: 'Jonathan Burkardt', p: 'FWD', c: 'Eintracht Frankfurt' },
    ],
  },
  'Curaçao': {
    coach: 'Dick Advocaat',
    players: [
      { n: 'Eloy Room', p: 'GK', c: 'Columbus Crew' },
      { n: 'Kevin Jansen', p: 'GK', c: 'Almere City' },
      { n: 'Marvin Zeegelaar', p: 'DEF', c: 'Free agent' },
      { n: 'Cuco Martina', p: 'DEF', c: 'Free agent' },
      { n: 'Shurandy Sambo', p: 'DEF', c: 'PEC Zwolle' },
      { n: 'Juninho Bacuna', p: 'MID', c: 'Birmingham City' },
      { n: 'Leandro Bacuna', p: 'MID', c: 'Free agent' },
      { n: 'Roshon van Eijma', p: 'DEF', c: 'Heerenveen' },
      { n: 'Sherel Floranus', p: 'DEF', c: 'Almere City' },
      { n: 'Armando Obispo', p: 'DEF', c: 'PSV Eindhoven' },
      { n: 'Jürgen Locadia', p: 'FWD', c: 'PEC Zwolle' },
      { n: 'Tahith Chong', p: 'MID', c: 'Sheffield United' },
      { n: 'Jeremy Antonisse', p: 'MID', c: 'Excelsior' },
      { n: 'Kenji Gorré', p: 'MID', c: 'Nacional' },
      { n: 'Brem Soumaoro', p: 'DEF', c: 'Lommel' },
      { n: 'Gervane Kastaneer', p: 'FWD', c: 'Ural' },
      { n: 'Sontje Hansen', p: 'FWD', c: 'Middlesbrough' },
      { n: 'Ar\'jany Martha', p: 'FWD', c: 'Ajax' },
      { n: 'Livano Comenencia', p: 'DEF', c: 'Juventus' },
      { n: 'Rangelo Janga', p: 'FWD', c: 'CSKA Sofia' },
      { n: 'Vurnon Anita', p: 'MID', c: 'Free agent' },
      { n: 'Anfernee Dijksteel', p: 'DEF', c: 'Middlesbrough' },
      { n: 'Nigel Hasselbaink', p: 'FWD', c: 'PEC Zwolle' },
      { n: 'Darren Sidoel', p: 'DEF', c: 'Roda JC' },
      { n: 'Jearl Margaritha', p: 'FWD', c: 'FC Eindhoven' },
      { n: 'Kenneth Dougall', p: 'MID', c: 'Blackpool' },
    ],
  },
  "Côte d'Ivoire": {
    coach: 'Emerse Faé',
    players: [
      { n: 'Yahia Fofana', p: 'GK', c: 'Angers' },
      { n: 'Badra Ali Sangaré', p: 'GK', c: 'ASEC Mimosas' },
      { n: 'Mohamed Koné', p: 'GK', c: 'Stade Tunisien' },
      { n: 'Odilon Kossounou', p: 'DEF', c: 'Atalanta' },
      { n: 'Willy Boly', p: 'DEF', c: 'Al-Shabab' },
      { n: 'Evan Ndicka', p: 'DEF', c: 'Roma' },
      { n: 'Ousmane Diomandé', p: 'DEF', c: 'Sporting CP' },
      { n: 'Ghislain Konan', p: 'DEF', c: 'Al-Bukayriyah' },
      { n: 'Wilfried Singo', p: 'DEF', c: 'Monaco' },
      { n: 'Serge Aurier', p: 'DEF', c: 'Free agent' },
      { n: 'Franck Kessié', p: 'MID', c: 'Al-Ahli' },
      { n: 'Ibrahim Sangaré', p: 'MID', c: 'Nottingham Forest' },
      { n: 'Seko Fofana', p: 'MID', c: 'Rennes' },
      { n: 'Jean-Michaël Seri', p: 'MID', c: 'Al-Gharafa' },
      { n: 'Yves Bissouma', p: 'MID', c: 'Tottenham Hotspur' },
      { n: 'Lazare Amani', p: 'MID', c: 'Union SG' },
      { n: 'Sébastien Haller', p: 'FWD', c: 'Utrecht' },
      { n: 'Wilfried Zaha', p: 'FWD', c: 'Charlotte FC' },
      { n: 'Nicolas Pépé', p: 'FWD', c: 'Villarreal' },
      { n: 'Jérémie Boga', p: 'FWD', c: 'Nice' },
      { n: 'Simon Adingra', p: 'FWD', c: 'Sunderland' },
      { n: 'Amad Diallo', p: 'FWD', c: 'Manchester United' },
      { n: 'Jean-Philippe Krasso', p: 'FWD', c: 'Panathinaikos' },
      { n: 'Karim Konaté', p: 'FWD', c: 'Red Bull Salzburg' },
      { n: 'Oumar Diakité', p: 'FWD', c: 'Reims' },
      { n: 'David Datro Fofana', p: 'FWD', c: 'Chelsea' },
    ],
  },
  'Ecuador': {
    coach: 'Sebastián Beccacece',
    players: [
      { n: 'Hernán Galíndez', p: 'GK', c: 'Huracán' },
      { n: 'Alexander Domínguez', p: 'GK', c: 'LDU Quito' },
      { n: 'Gonzalo Valle', p: 'GK', c: 'LDU Quito' },
      { n: 'Pervis Estupiñán', p: 'DEF', c: 'AC Milan' },
      { n: 'Piero Hincapié', p: 'DEF', c: 'Arsenal' },
      { n: 'Willian Pacho', p: 'DEF', c: 'Paris Saint-Germain' },
      { n: 'Joel Ordóñez', p: 'DEF', c: 'Club Brugge' },
      { n: 'Félix Torres', p: 'DEF', c: 'Corinthians' },
      { n: 'Ángelo Preciado', p: 'DEF', c: 'Sparta Prague' },
      { n: 'Diego Palacios', p: 'DEF', c: 'Corinthians' },
      { n: 'Moisés Caicedo', p: 'MID', c: 'Chelsea' },
      { n: 'Alan Franco', p: 'MID', c: 'Al-Rayyan' },
      { n: 'Jhegson Méndez', p: 'MID', c: 'LDU Quito' },
      { n: 'José Cifuentes', p: 'MID', c: 'Rangers' },
      { n: 'Patrik Mercado', p: 'MID', c: 'LDU Quito' },
      { n: 'Kendry Páez', p: 'MID', c: 'Chelsea' },
      { n: 'Pedro Vite', p: 'MID', c: 'Vancouver Whitecaps' },
      { n: 'Enner Valencia', p: 'FWD', c: 'Internacional' },
      { n: 'Kevin Rodríguez', p: 'FWD', c: 'Union SG' },
      { n: 'Gonzalo Plata', p: 'FWD', c: 'Flamengo' },
      { n: 'Djorkaeff Reasco', p: 'DEF', c: 'Newell\'s Old Boys' },
      { n: 'Jeremy Sarmiento', p: 'FWD', c: 'Brighton' },
      { n: 'Nilson Angulo', p: 'FWD', c: 'Anderlecht' },
      { n: 'John Yeboah', p: 'FWD', c: 'Vancouver Whitecaps' },
      { n: 'Leonardo Campana', p: 'FWD', c: 'Inter Miami' },
      { n: 'Ángel Mena', p: 'MID', c: 'León' },
    ],
  },
  // ---------------- GROUP F ----------------
  'Netherlands': {
    coach: 'Ronald Koeman',
    players: [
      { n: 'Bart Verbruggen', p: 'GK', c: 'Brighton' },
      { n: 'Mark Flekken', p: 'GK', c: 'Bayer Leverkusen' },
      { n: 'Nick Olij', p: 'GK', c: 'Sparta Rotterdam' },
      { n: 'Denzel Dumfries', p: 'DEF', c: 'Inter Milan' },
      { n: 'Virgil van Dijk', p: 'DEF', c: 'Liverpool' },
      { n: 'Stefan de Vrij', p: 'DEF', c: 'Inter Milan' },
      { n: 'Matthijs de Ligt', p: 'DEF', c: 'Manchester United' },
      { n: 'Nathan Aké', p: 'DEF', c: 'Manchester City' },
      { n: 'Lutsharel Geertruida', p: 'DEF', c: 'RB Leipzig' },
      { n: 'Jurriën Timber', p: 'DEF', c: 'Arsenal' },
      { n: 'Jorrel Hato', p: 'DEF', c: 'Chelsea' },
      { n: 'Frenkie de Jong', p: 'MID', c: 'Barcelona' },
      { n: 'Tijjani Reijnders', p: 'MID', c: 'Manchester City' },
      { n: 'Ryan Gravenberch', p: 'MID', c: 'Liverpool' },
      { n: 'Jerdy Schouten', p: 'MID', c: 'PSV Eindhoven' },
      { n: 'Xavi Simons', p: 'MID', c: 'Tottenham Hotspur' },
      { n: 'Quinten Timber', p: 'MID', c: 'Feyenoord' },
      { n: 'Cody Gakpo', p: 'FWD', c: 'Liverpool' },
      { n: 'Memphis Depay', p: 'FWD', c: 'Corinthians' },
      { n: 'Donyell Malen', p: 'FWD', c: 'Aston Villa' },
      { n: 'Wout Weghorst', p: 'FWD', c: 'Ajax' },
      { n: 'Brian Brobbey', p: 'FWD', c: 'Sunderland' },
      { n: 'Joshua Zirkzee', p: 'FWD', c: 'Manchester United' },
      { n: 'Noa Lang', p: 'FWD', c: 'PSV Eindhoven' },
      { n: 'Emanuel Emegha', p: 'FWD', c: 'Strasbourg' },
      { n: 'Ian Maatsen', p: 'DEF', c: 'Aston Villa' },
    ],
  },
  'Japan': {
    coach: 'Hajime Moriyasu',
    players: [
      { n: 'Zion Suzuki', p: 'GK', c: 'Parma' },
      { n: 'Daniel Schmidt', p: 'GK', c: 'Sint-Truiden' },
      { n: 'Keisuke Osako', p: 'GK', c: 'Sanfrecce Hiroshima' },
      { n: 'Hiroki Ito', p: 'DEF', c: 'Bayern Munich' },
      { n: 'Ko Itakura', p: 'DEF', c: "Borussia Mönchengladbach" },
      { n: 'Takehiro Tomiyasu', p: 'DEF', c: 'Arsenal' },
      { n: 'Shogo Taniguchi', p: 'DEF', c: 'Sint-Truiden' },
      { n: 'Yukinari Sugawara', p: 'DEF', c: 'Southampton' },
      { n: 'Hiroki Sakai', p: 'DEF', c: 'Cerezo Osaka' },
      { n: 'Yuta Nakayama', p: 'DEF', c: 'Machida Zelvia' },
      { n: 'Wataru Endo', p: 'MID', c: 'Liverpool' },
      { n: 'Hidemasa Morita', p: 'MID', c: 'Sporting CP' },
      { n: 'Ao Tanaka', p: 'MID', c: 'Leeds United' },
      { n: 'Daichi Kamada', p: 'MID', c: 'Crystal Palace' },
      { n: 'Takefusa Kubo', p: 'MID', c: 'Real Sociedad' },
      { n: 'Ritsu Doan', p: 'MID', c: 'Eintracht Frankfurt' },
      { n: 'Junya Ito', p: 'MID', c: 'Stade Reims' },
      { n: 'Kaoru Mitoma', p: 'FWD', c: 'Brighton' },
      { n: 'Takumi Minamino', p: 'MID', c: 'Monaco' },
      { n: 'Ayase Ueda', p: 'FWD', c: 'Feyenoord' },
      { n: 'Daizen Maeda', p: 'FWD', c: 'Celtic' },
      { n: 'Koki Ogawa', p: 'FWD', c: 'NEC Nijmegen' },
      { n: 'Shuto Machino', p: 'FWD', c: 'Holstein Kiel' },
      { n: 'Reo Hatate', p: 'MID', c: 'Celtic' },
      { n: 'Keito Nakamura', p: 'FWD', c: 'Stade Reims' },
      { n: 'Seiya Maikuma', p: 'DEF', c: 'Cerezo Osaka' },
    ],
  },
  'Sweden': {
    coach: 'Graham Potter',
    players: [
      { n: 'Robin Olsen', p: 'GK', c: 'Aston Villa' },
      { n: 'Kristoffer Nordfeldt', p: 'GK', c: 'Brommapojkarna' },
      { n: 'Viktor Johansson', p: 'GK', c: 'Stoke City' },
      { n: 'Emil Krafth', p: 'DEF', c: 'Newcastle United' },
      { n: 'Victor Lindelöf', p: 'DEF', c: 'Aston Villa' },
      { n: 'Isak Hien', p: 'DEF', c: 'Aston Villa' },
      { n: 'Gabriel Gudmundsson', p: 'DEF', c: 'Leeds United' },
      { n: 'Ludwig Augustinsson', p: 'DEF', c: 'Mallorca' },
      { n: 'Hjalmar Ekdal', p: 'DEF', c: 'Burnley' },
      { n: 'Daniel Svensson', p: 'DEF', c: 'Borussia Dortmund' },
      { n: 'Albin Ekdal', p: 'MID', c: 'Spezia' },
      { n: 'Mattias Svanberg', p: 'MID', c: 'Wolfsburg' },
      { n: 'Kristoffer Olsson', p: 'MID', c: 'FC Copenhagen' },
      { n: 'Jens Cajuste', p: 'MID', c: 'Ipswich Town' },
      { n: 'Lasse Nielsen', p: 'MID', c: 'Malmö FF' },
      { n: 'Yasin Ayari', p: 'MID', c: 'Brighton' },
      { n: 'Hugo Larsson', p: 'MID', c: 'Eintracht Frankfurt' },
      { n: 'Dejan Kulusevski', p: 'MID', c: 'Tottenham Hotspur' },
      { n: 'Anthony Elanga', p: 'FWD', c: 'Newcastle United' },
      { n: 'Alexander Isak', p: 'FWD', c: 'Liverpool' },
      { n: 'Viktor Gyökeres', p: 'FWD', c: 'Arsenal' },
      { n: 'Emil Forsberg', p: 'MID', c: 'New York Red Bulls' },
      { n: 'Jesper Karlsson', p: 'FWD', c: 'Lens' },
      { n: 'Sebastian Nanasi', p: 'FWD', c: 'Strasbourg' },
      { n: 'Roony Bardghji', p: 'FWD', c: 'Barcelona' },
      { n: 'Gustav Nilsson', p: 'FWD', c: 'Sparta Prague' },
    ],
  },
  'Tunisia': {
    coach: 'Sami Trabelsi',
    players: [
      { n: 'Aymen Dahmen', p: 'GK', c: 'CS Sfaxien' },
      { n: 'Béchir Ben Saïd', p: 'GK', c: 'US Monastir' },
      { n: 'Aymen Mathlouthi', p: 'GK', c: 'Étoile du Sahel' },
      { n: 'Mohamed Dräger', p: 'DEF', c: 'Espérance' },
      { n: 'Montassar Talbi', p: 'DEF', c: 'Lorient' },
      { n: 'Yassine Meriah', p: 'DEF', c: 'Espérance' },
      { n: 'Dylan Bronn', p: 'DEF', c: 'Salernitana' },
      { n: 'Ali Abdi', p: 'DEF', c: 'Caen' },
      { n: 'Wajdi Kechrida', p: 'DEF', c: 'Atromitos' },
      { n: 'Nader Ghandri', p: 'DEF', c: 'Antalyaspor' },
      { n: 'Aïssa Laïdouni', p: 'MID', c: 'Wolfsburg' },
      { n: 'Ellyes Skhiri', p: 'MID', c: 'Eintracht Frankfurt' },
      { n: 'Hannibal Mejbri', p: 'MID', c: 'Burnley' },
      { n: 'Ferjani Sassi', p: 'MID', c: 'Al-Duhail' },
      { n: 'Mohamed Ali Ben Romdhane', p: 'MID', c: 'Ferencváros' },
      { n: 'Saîf-Eddine Khaoui', p: 'MID', c: 'Espérance' },
      { n: 'Anis Ben Slimane', p: 'MID', c: 'Sheffield United' },
      { n: 'Youssef Msakni', p: 'FWD', c: 'Al-Arabi' },
      { n: 'Naïm Sliti', p: 'FWD', c: 'Al-Ettifaq' },
      { n: 'Elias Achouri', p: 'FWD', c: 'FC Copenhagen' },
      { n: 'Seifeddine Jaziri', p: 'FWD', c: 'Zamalek' },
      { n: 'Hamza Rafia', p: 'MID', c: 'Lecce' },
      { n: 'Firas Chaouat', p: 'FWD', c: 'Espérance' },
      { n: 'Omar Layouni', p: 'FWD', c: 'Espérance' },
      { n: 'Haythem Jouini', p: 'FWD', c: 'Espérance' },
      { n: 'Ali Maâloul', p: 'DEF', c: 'Al-Ahly' },
    ],
  },
  // ---------------- GROUP G ----------------
  'Belgium': {
    coach: 'Rudi Garcia',
    players: [
      { n: 'Thibaut Courtois', p: 'GK', c: 'Real Madrid' },
      { n: 'Matz Sels', p: 'GK', c: 'Nottingham Forest' },
      { n: 'Koen Casteels', p: 'GK', c: 'Al-Qadsiah' },
      { n: 'Timothy Castagne', p: 'DEF', c: 'Fulham' },
      { n: 'Zeno Debast', p: 'DEF', c: 'Sporting CP' },
      { n: 'Wout Faes', p: 'DEF', c: 'Leicester City' },
      { n: 'Maxim De Cuyper', p: 'DEF', c: 'Brighton' },
      { n: 'Brandon Mechele', p: 'DEF', c: 'Club Brugge' },
      { n: 'Joaquin Seys', p: 'DEF', c: 'Club Brugge' },
      { n: 'Koni De Winter', p: 'DEF', c: 'AC Milan' },
      { n: 'Youri Tielemans', p: 'MID', c: 'Aston Villa' },
      { n: 'Amadou Onana', p: 'MID', c: 'Aston Villa' },
      { n: 'Hans Vanaken', p: 'MID', c: 'Club Brugge' },
      { n: 'Nicolas Raskin', p: 'MID', c: 'Rangers' },
      { n: 'Charles De Ketelaere', p: 'MID', c: 'Atalanta' },
      { n: 'Arthur Vermeeren', p: 'MID', c: 'RB Leipzig' },
      { n: 'Kevin De Bruyne', p: 'MID', c: 'Napoli' },
      { n: 'Jérémy Doku', p: 'FWD', c: 'Manchester City' },
      { n: 'Leandro Trossard', p: 'FWD', c: 'Arsenal' },
      { n: 'Dodi Lukebakio', p: 'FWD', c: 'Sevilla' },
      { n: 'Johan Bakayoko', p: 'FWD', c: 'RB Leipzig' },
      { n: 'Romelu Lukaku', p: 'FWD', c: 'Napoli' },
      { n: 'Loïs Openda', p: 'FWD', c: 'Juventus' },
      { n: 'Charles Vanhoutte', p: 'MID', c: 'Marseille' },
      { n: 'Maxim Dewaele', p: 'MID', c: 'OH Leuven' },
      { n: 'Thomas Meunier', p: 'DEF', c: 'Lille' },
    ],
  },
  'Egypt': {
    coach: 'Hossam Hassan',
    players: [
      { n: 'Mohamed El Shenawy', p: 'GK', c: 'Al Ahly' },
      { n: 'Mohamed Sobhi', p: 'GK', c: 'Pyramids' },
      { n: 'Mohamed Bassam', p: 'GK', c: 'Zamalek' },
      { n: 'Ahmed Hegazi', p: 'DEF', c: 'Al-Ittihad' },
      { n: 'Mohamed Abdelmonem', p: 'DEF', c: 'Al Ahly' },
      { n: 'Omar Kamal', p: 'DEF', c: 'Al Ahly' },
      { n: 'Ahmed Fattouh', p: 'DEF', c: 'Zamalek' },
      { n: 'Mohamed Hany', p: 'DEF', c: 'Al Ahly' },
      { n: 'Ahmed Ramadan', p: 'DEF', c: 'Pyramids' },
      { n: 'Rami Rabia', p: 'DEF', c: 'Al Ahly' },
      { n: 'Mohamed Elneny', p: 'MID', c: 'Al-Jazira' },
      { n: 'Marwan Attia', p: 'MID', c: 'Al Ahly' },
      { n: 'Nabil Emad', p: 'MID', c: 'Pyramids' },
      { n: 'Emam Ashour', p: 'MID', c: 'Al Ahly' },
      { n: 'Mahmoud Saber', p: 'MID', c: 'Al Ahly' },
      { n: 'Mostafa Fathi', p: 'MID', c: 'Zamalek' },
      { n: 'Mohamed Salah', p: 'FWD', c: 'Liverpool' },
      { n: 'Omar Marmoush', p: 'FWD', c: 'Manchester City' },
      { n: 'Trézéguet', p: 'FWD', c: 'Al Ahly' },
      { n: 'Mostafa Mohamed', p: 'FWD', c: 'Nantes' },
      { n: 'Ahmed Sayed Zizo', p: 'FWD', c: 'Al Ahly' },
      { n: 'Ibrahim Adel', p: 'FWD', c: 'Pyramids' },
      { n: 'Mohamed Sherif', p: 'FWD', c: 'Al Ahly' },
      { n: 'Salah Mohsen', p: 'FWD', c: 'Al Ahly' },
      { n: 'Mahmoud Hassan', p: 'MID', c: 'Pyramids' },
      { n: 'Akram Tawfik', p: 'DEF', c: 'Al Ahly' },
    ],
  },
  'Iran': {
    coach: 'Amir Ghalenoei',
    players: [
      { n: 'Alireza Beiranvand', p: 'GK', c: 'Tractor' },
      { n: 'Payam Niazmand', p: 'GK', c: 'Sepahan' },
      { n: 'Hossein Hosseini', p: 'GK', c: 'Esteghlal' },
      { n: 'Sadegh Moharrami', p: 'DEF', c: 'Dinamo Zagreb' },
      { n: 'Shojae Khalilzadeh', p: 'DEF', c: 'Tractor' },
      { n: 'Majid Hosseini', p: 'DEF', c: 'Esteghlal' },
      { n: 'Aref Aghasi', p: 'DEF', c: 'Sepahan' },
      { n: 'Milad Mohammadi', p: 'DEF', c: 'AEK Athens' },
      { n: 'Hossein Kanaanizadegan', p: 'DEF', c: 'Al-Ahli Doha' },
      { n: 'Ramin Rezaeian', p: 'DEF', c: 'Esteghlal' },
      { n: 'Saeid Ezatolahi', p: 'MID', c: 'Esteghlal' },
      { n: 'Ahmad Nourollahi', p: 'MID', c: 'Shabab Al-Ahli' },
      { n: 'Omid Noorafkan', p: 'MID', c: 'Sepahan' },
      { n: 'Mehdi Ghayedi', p: 'MID', c: 'Ittihad Kalba' },
      { n: 'Alireza Jahanbakhsh', p: 'MID', c: 'Heerenveen' },
      { n: 'Saman Ghoddos', p: 'MID', c: 'Brentford' },
      { n: 'Mohammad Mohebi', p: 'MID', c: 'Rostov' },
      { n: 'Mehdi Taremi', p: 'FWD', c: 'Inter Milan' },
      { n: 'Sardar Azmoun', p: 'FWD', c: 'Shabab Al-Ahli' },
      { n: 'Karim Ansarifard', p: 'FWD', c: 'Esteghlal' },
      { n: 'Allahyar Sayyadmanesh', p: 'FWD', c: 'Westerlo' },
      { n: 'Shahriyar Moghanlou', p: 'FWD', c: 'Persepolis' },
      { n: 'Mohammad Karimi', p: 'MID', c: 'Sepahan' },
      { n: 'Ali Gholizadeh', p: 'FWD', c: 'Lech Poznań' },
      { n: 'Abolfazl Jalali', p: 'DEF', c: 'Esteghlal' },
      { n: 'Amirhossein Hosseinzadeh', p: 'FWD', c: 'Tractor' },
    ],
  },
  'New Zealand': {
    coach: 'Darren Bazeley',
    players: [
      { n: 'Max Crocombe', p: 'GK', c: 'Burton Albion' },
      { n: 'Alex Paulsen', p: 'GK', c: 'Auckland FC' },
      { n: 'Nik Tzanev', p: 'GK', c: 'AFC Wimbledon' },
      { n: 'Tyler Bindon', p: 'DEF', c: 'Reading' },
      { n: 'Finn Surman', p: 'DEF', c: 'Portland Timbers' },
      { n: 'Michael Boxall', p: 'DEF', c: 'Minnesota United' },
      { n: 'Nando Pijnaker', p: 'DEF', c: 'St. Mirren' },
      { n: 'Liberato Cacace', p: 'DEF', c: 'Empoli' },
      { n: 'Tim Payne', p: 'DEF', c: 'Auckland FC' },
      { n: 'Dane Ingham', p: 'DEF', c: 'Wellington Phoenix' },
      { n: 'Joe Bell', p: 'MID', c: 'Viking' },
      { n: 'Marko Stamenic', p: 'MID', c: 'Olympiacos' },
      { n: 'Matthew Garbett', p: 'MID', c: 'NAC Breda' },
      { n: 'Clayton Lewis', p: 'MID', c: 'Auckland FC' },
      { n: 'Alex Greive', p: 'FWD', c: 'St. Mirren' },
      { n: 'Sarpreet Singh', p: 'MID', c: 'Hapoel Beer Sheva' },
      { n: 'Ben Old', p: 'MID', c: 'St. Mirren' },
      { n: 'Chris Wood', p: 'FWD', c: 'Nottingham Forest' },
      { n: 'Kosta Barbarouses', p: 'FWD', c: 'Auckland FC' },
      { n: 'Elijah Just', p: 'FWD', c: 'Odense' },
      { n: 'Ben Waine', p: 'FWD', c: 'Plymouth Argyle' },
      { n: 'Bill Tuiloma', p: 'DEF', c: 'Charlotte FC' },
      { n: 'Callum McCowatt', p: 'FWD', c: 'Auckland FC' },
      { n: 'Matthew Conroy', p: 'DEF', c: 'Western United' },
      { n: 'Storm Roux', p: 'DEF', c: 'Auckland FC' },
      { n: 'Oliver Whyte', p: 'MID', c: 'Wellington Phoenix' },
    ],
  },
  // ---------------- GROUP H ----------------
  'Spain': {
    coach: 'Luis de la Fuente',
    players: [
      { n: 'Unai Simón', p: 'GK', c: 'Athletic Bilbao' },
      { n: 'David Raya', p: 'GK', c: 'Arsenal' },
      { n: 'Álex Remiro', p: 'GK', c: 'Real Sociedad' },
      { n: 'Pedro Porro', p: 'DEF', c: 'Tottenham Hotspur' },
      { n: 'Dani Carvajal', p: 'DEF', c: 'Real Madrid' },
      { n: 'Robin Le Normand', p: 'DEF', c: 'Atlético Madrid' },
      { n: 'Pau Cubarsí', p: 'DEF', c: 'Barcelona' },
      { n: 'Dean Huijsen', p: 'DEF', c: 'Real Madrid' },
      { n: 'Marc Cucurella', p: 'DEF', c: 'Chelsea' },
      { n: 'Alejandro Grimaldo', p: 'DEF', c: 'Bayer Leverkusen' },
      { n: 'Aymeric Laporte', p: 'DEF', c: 'Athletic Bilbao' },
      { n: 'Rodri', p: 'MID', c: 'Manchester City' },
      { n: 'Martín Zubimendi', p: 'MID', c: 'Arsenal' },
      { n: 'Pedri', p: 'MID', c: 'Barcelona' },
      { n: 'Fabián Ruiz', p: 'MID', c: 'Paris Saint-Germain' },
      { n: 'Mikel Merino', p: 'MID', c: 'Arsenal' },
      { n: 'Dani Olmo', p: 'MID', c: 'Barcelona' },
      { n: 'Lamine Yamal', p: 'FWD', c: 'Barcelona' },
      { n: 'Nico Williams', p: 'FWD', c: 'Athletic Bilbao' },
      { n: 'Mikel Oyarzabal', p: 'FWD', c: 'Real Sociedad' },
      { n: 'Álvaro Morata', p: 'FWD', c: 'Como' },
      { n: 'Ferran Torres', p: 'FWD', c: 'Barcelona' },
      { n: 'Yeremy Pino', p: 'FWD', c: 'Crystal Palace' },
      { n: 'Samu Aghehowa', p: 'FWD', c: 'Porto' },
      { n: 'Ayoze Pérez', p: 'FWD', c: 'Villarreal' },
      { n: 'Fermín López', p: 'MID', c: 'Barcelona' },
    ],
  },
  'Cabo Verde': {
    coach: 'Pedro Leitão Brito (Bubista)',
    players: [
      { n: 'Vozinha', p: 'GK', c: 'AVS' },
      { n: 'Bruno Varela', p: 'GK', c: 'Vitória Guimarães' },
      { n: 'Márcio Rosa', p: 'GK', c: 'Rio Ave' },
      { n: 'Diney Borges', p: 'DEF', c: 'Estoril' },
      { n: 'Roberto Lopes', p: 'DEF', c: 'Shamrock Rovers' },
      { n: 'Stopira', p: 'DEF', c: 'Free agent' },
      { n: 'Logan Costa', p: 'DEF', c: 'Toulouse' },
      { n: 'Kenny Rocha Santos', p: 'DEF', c: 'AEK Larnaca' },
      { n: 'Steven Moreira', p: 'DEF', c: 'Columbus Crew' },
      { n: 'Cláudio Gomes', p: 'DEF', c: 'Palermo' },
      { n: 'Jamiro Monteiro', p: 'MID', c: 'San Jose Earthquakes' },
      { n: 'Kevin Pina', p: 'MID', c: 'Casa Pia' },
      { n: 'Deroy Duarte', p: 'MID', c: 'Sparta Rotterdam' },
      { n: 'Laros Duarte', p: 'MID', c: 'Sparta Rotterdam' },
      { n: 'Pico', p: 'MID', c: 'Casa Pia' },
      { n: 'Gilson Benchimol', p: 'MID', c: 'Vitória Guimarães' },
      { n: 'Dailon Livramento', p: 'FWD', c: 'Casa Pia' },
      { n: 'Ryan Mendes', p: 'FWD', c: 'Al-Wakrah' },
      { n: 'Garry Rodrigues', p: 'FWD', c: 'Free agent' },
      { n: 'Bebé', p: 'FWD', c: 'Rio Ave' },
      { n: 'Júlio Tavares', p: 'FWD', c: 'Free agent' },
      { n: 'Willy Semedo', p: 'FWD', c: 'Sepsi OSK' },
      { n: 'Gilberto', p: 'FWD', c: 'Casa Pia' },
      { n: 'Yannick Semedo', p: 'MID', c: 'Estrela Amadora' },
      { n: 'Telma Encarnação', p: 'FWD', c: 'Marítimo' },
      { n: 'Sidny Cabral', p: 'DEF', c: 'Anorthosis' },
    ],
  },
  'Saudi Arabia': {
    coach: 'Hervé Renard',
    players: [
      { n: 'Nawaf Al-Aqidi', p: 'GK', c: 'Al-Nassr' },
      { n: 'Mohammed Al-Owais', p: 'GK', c: 'Al-Hilal' },
      { n: 'Ahmed Al-Kassar', p: 'GK', c: 'Al-Ettifaq' },
      { n: 'Saud Abdulhamid', p: 'DEF', c: 'Roma' },
      { n: 'Sultan Al-Ghannam', p: 'DEF', c: 'Al-Nassr' },
      { n: 'Ali Al-Bulaihi', p: 'DEF', c: 'Al-Hilal' },
      { n: 'Hassan Tambakti', p: 'DEF', c: 'Al-Hilal' },
      { n: 'Abdulelah Al-Amri', p: 'DEF', c: 'Al-Nassr' },
      { n: 'Yasser Al-Shahrani', p: 'DEF', c: 'Al-Hilal' },
      { n: 'Metab Al-Buraik', p: 'DEF', c: 'Al-Hilal' },
      { n: 'Nasser Al-Dawsari', p: 'MID', c: 'Al-Hilal' },
      { n: 'Mohamed Kanno', p: 'MID', c: 'Al-Hilal' },
      { n: 'Ali Al-Hassan', p: 'MID', c: 'Al-Nassr' },
      { n: 'Musab Al-Juwayr', p: 'MID', c: 'Al-Hilal' },
      { n: 'Sami Al-Najei', p: 'MID', c: 'Al-Nassr' },
      { n: 'Abdullah Otayf', p: 'MID', c: 'Al-Shabab' },
      { n: 'Salem Al-Dawsari', p: 'FWD', c: 'Al-Hilal' },
      { n: 'Firas Al-Buraikan', p: 'FWD', c: 'Al-Ahli' },
      { n: 'Saleh Al-Shehri', p: 'FWD', c: 'Al-Hilal' },
      { n: 'Abdullah Al-Hamdan', p: 'FWD', c: 'Al-Hilal' },
      { n: 'Marwan Al-Sahafi', p: 'FWD', c: 'Al-Ahli' },
      { n: 'Abdulrahman Ghareeb', p: 'FWD', c: 'Al-Ahli' },
      { n: 'Hatan Bahbri', p: 'FWD', c: 'Al-Shabab' },
      { n: 'Ayman Yahya', p: 'MID', c: 'Al-Nassr' },
      { n: 'Riyadh Sharahili', p: 'DEF', c: 'Al-Ahli' },
      { n: 'Faisal Al-Ghamdi', p: 'MID', c: 'Al-Ahli' },
    ],
  },
  'Uruguay': {
    coach: 'Marcelo Bielsa',
    players: [
      { n: 'Sergio Rochet', p: 'GK', c: 'Internacional' },
      { n: 'Santiago Mele', p: 'GK', c: 'Junior' },
      { n: 'Franco Israel', p: 'GK', c: 'Sporting CP' },
      { n: 'Ronald Araújo', p: 'DEF', c: 'Barcelona' },
      { n: 'José María Giménez', p: 'DEF', c: 'Atlético Madrid' },
      { n: 'Sebastián Cáceres', p: 'DEF', c: 'América' },
      { n: 'Mathías Olivera', p: 'DEF', c: 'Napoli' },
      { n: 'Nahitan Nández', p: 'DEF', c: 'Al-Qadsiah' },
      { n: 'Guillermo Varela', p: 'DEF', c: 'Flamengo' },
      { n: 'Santiago Bueno', p: 'DEF', c: 'Wolverhampton' },
      { n: 'Federico Valverde', p: 'MID', c: 'Real Madrid' },
      { n: 'Manuel Ugarte', p: 'MID', c: 'Manchester United' },
      { n: 'Rodrigo Bentancur', p: 'MID', c: 'Tottenham Hotspur' },
      { n: 'Nicolás de la Cruz', p: 'MID', c: 'Flamengo' },
      { n: 'Giorgian de Arrascaeta', p: 'MID', c: 'Flamengo' },
      { n: 'Rodrigo Zalazar', p: 'MID', c: 'Braga' },
      { n: 'Facundo Pellistri', p: 'FWD', c: 'Panathinaikos' },
      { n: 'Federico Viñas', p: 'FWD', c: 'León' },
      { n: 'Darwin Núñez', p: 'FWD', c: 'Al-Hilal' },
      { n: 'Maxi Araújo', p: 'FWD', c: 'Sporting CP' },
      { n: 'Brian Rodríguez', p: 'FWD', c: 'América' },
      { n: 'Rodrigo Aguirre', p: 'FWD', c: 'América' },
      { n: 'Cristian Olivera', p: 'FWD', c: 'LAFC' },
      { n: 'Agustín Canobbio', p: 'FWD', c: 'Athletico Paranaense' },
      { n: 'César Araújo', p: 'MID', c: 'Orlando City' },
      { n: 'Emiliano Martínez', p: 'MID', c: 'Midtjylland' },
    ],
  },
  // ---------------- GROUP I ----------------
  'France': {
    coach: 'Didier Deschamps',
    players: [
      { n: 'Mike Maignan', p: 'GK', c: 'AC Milan' },
      { n: 'Brice Samba', p: 'GK', c: 'Rennes' },
      { n: 'Lucas Chevalier', p: 'GK', c: 'Paris Saint-Germain' },
      { n: 'Jules Koundé', p: 'DEF', c: 'Barcelona' },
      { n: 'William Saliba', p: 'DEF', c: 'Arsenal' },
      { n: 'Dayot Upamecano', p: 'DEF', c: 'Bayern Munich' },
      { n: 'Ibrahima Konaté', p: 'DEF', c: 'Liverpool' },
      { n: 'Theo Hernández', p: 'DEF', c: 'Al-Hilal' },
      { n: 'Lucas Hernández', p: 'DEF', c: 'Paris Saint-Germain' },
      { n: 'Lucas Digne', p: 'DEF', c: 'Aston Villa' },
      { n: 'Malo Gusto', p: 'DEF', c: 'Chelsea' },
      { n: 'Aurélien Tchouaméni', p: 'MID', c: 'Real Madrid' },
      { n: 'Eduardo Camavinga', p: 'MID', c: 'Real Madrid' },
      { n: 'Adrien Rabiot', p: 'MID', c: 'AC Milan' },
      { n: 'Manu Koné', p: 'MID', c: 'Roma' },
      { n: 'Warren Zaïre-Emery', p: 'MID', c: 'Paris Saint-Germain' },
      { n: 'Khéphren Thuram', p: 'MID', c: 'Juventus' },
      { n: 'Kylian Mbappé', p: 'FWD', c: 'Real Madrid' },
      { n: 'Ousmane Dembélé', p: 'FWD', c: 'Paris Saint-Germain' },
      { n: 'Michael Olise', p: 'FWD', c: 'Bayern Munich' },
      { n: 'Bradley Barcola', p: 'FWD', c: 'Paris Saint-Germain' },
      { n: 'Marcus Thuram', p: 'FWD', c: 'Inter Milan' },
      { n: 'Randal Kolo Muani', p: 'FWD', c: 'Juventus' },
      { n: 'Hugo Ekitiké', p: 'FWD', c: 'Liverpool' },
      { n: 'Christopher Nkunku', p: 'FWD', c: 'AC Milan' },
      { n: 'Désiré Doué', p: 'FWD', c: 'Paris Saint-Germain' },
    ],
  },
  'Senegal': {
    coach: 'Pape Thiaw',
    players: [
      { n: 'Édouard Mendy', p: 'GK', c: 'Al-Ahli' },
      { n: 'Seny Dieng', p: 'GK', c: 'Middlesbrough' },
      { n: 'Mory Diaw', p: 'GK', c: 'Clermont' },
      { n: 'Kalidou Koulibaly', p: 'DEF', c: 'Al-Hilal' },
      { n: 'Abdou Diallo', p: 'DEF', c: 'Al-Arabi' },
      { n: 'Moussa Niakhaté', p: 'DEF', c: 'Lyon' },
      { n: 'Antoine Mendy', p: 'DEF', c: 'Nice' },
      { n: 'Ismail Jakobs', p: 'DEF', c: 'Galatasaray' },
      { n: 'Krépin Diatta', p: 'DEF', c: 'Monaco' },
      { n: 'El Hadji Malick Diouf', p: 'DEF', c: 'West Ham United' },
      { n: 'Idrissa Gana Gueye', p: 'MID', c: 'Everton' },
      { n: 'Pape Matar Sarr', p: 'MID', c: 'Tottenham Hotspur' },
      { n: 'Pape Gueye', p: 'MID', c: 'Villarreal' },
      { n: 'Lamine Camara', p: 'MID', c: 'Monaco' },
      { n: 'Pathé Ciss', p: 'MID', c: 'Rayo Vallecano' },
      { n: 'Habib Diarra', p: 'MID', c: 'Sunderland' },
      { n: 'Sadio Mané', p: 'FWD', c: 'Al-Nassr' },
      { n: 'Ismaïla Sarr', p: 'FWD', c: 'Crystal Palace' },
      { n: 'Nicolas Jackson', p: 'FWD', c: 'Bayern Munich' },
      { n: 'Boulaye Dia', p: 'FWD', c: 'Lazio' },
      { n: 'Habib Diallo', p: 'FWD', c: 'Al-Shabab' },
      { n: 'Iliman Ndiaye', p: 'FWD', c: 'Everton' },
      { n: 'Cheikh Sabaly', p: 'FWD', c: 'Augsburg' },
      { n: 'Chérif Ndiaye', p: 'FWD', c: 'Étoile du Sahel' },
      { n: 'Formose Mendy', p: 'DEF', c: 'Amiens' },
      { n: 'Noah Fadiga', p: 'DEF', c: 'Brest' },
    ],
  },
  'Iraq': {
    coach: 'Graham Arnold',
    players: [
      { n: 'Jalal Hassan', p: 'GK', c: 'Al-Shorta' },
      { n: 'Ahmad Basil', p: 'GK', c: 'Al-Quwa Al-Jawiya' },
      { n: 'Fahad Talib', p: 'GK', c: 'Al-Zawraa' },
      { n: 'Merchas Doski', p: 'DEF', c: 'Duhok' },
      { n: 'Rebin Sulaka', p: 'DEF', c: 'Persita' },
      { n: 'Akam Hashim', p: 'DEF', c: 'Al-Shorta' },
      { n: 'Saad Natiq', p: 'DEF', c: 'Al-Quwa Al-Jawiya' },
      { n: 'Hussein Ali', p: 'DEF', c: 'Al-Zawraa' },
      { n: 'Zaid Tahseen', p: 'DEF', c: 'Al-Shorta' },
      { n: 'Mustafa Nadhim', p: 'DEF', c: 'Al-Quwa Al-Jawiya' },
      { n: 'Amir Al-Ammari', p: 'MID', c: 'Halmstad' },
      { n: 'Ibrahim Bayesh', p: 'MID', c: 'Al-Quwa Al-Jawiya' },
      { n: 'Bashar Resan', p: 'MID', c: 'Persepolis' },
      { n: 'Osama Rashid', p: 'MID', c: 'Vitória Guimarães' },
      { n: 'Zidane Iqbal', p: 'MID', c: 'Watford' },
      { n: 'Hassan Abdulkareem', p: 'MID', c: 'Al-Shorta' },
      { n: 'Sajjad Jassim', p: 'MID', c: 'Al-Quwa Al-Jawiya' },
      { n: 'Aymen Hussein', p: 'FWD', c: 'Al-Quwa Al-Jawiya' },
      { n: 'Mohanad Ali', p: 'FWD', c: 'Al-Shorta' },
      { n: 'Ali Jasim', p: 'FWD', c: 'Como' },
      { n: 'Mohammed Qasim', p: 'FWD', c: 'Al-Karkh' },
      { n: 'Manaf Younus', p: 'FWD', c: 'Al-Quwa Al-Jawiya' },
      { n: 'Youssef Amyn', p: 'FWD', c: 'Karlsruher SC' },
      { n: 'Ali Al-Hamadi', p: 'FWD', c: 'Ipswich Town' },
      { n: 'Hussein Jabbar', p: 'MID', c: 'Al-Najaf' },
      { n: 'Karrar Mohammed', p: 'DEF', c: 'Al-Shorta' },
    ],
  },
  'Norway': {
    coach: 'Ståle Solbakken',
    players: [
      { n: 'Ørjan Nyland', p: 'GK', c: 'Sevilla' },
      { n: 'Egil Selvik', p: 'GK', c: 'Brann' },
      { n: 'Mads Hedenstad', p: 'GK', c: 'Viking' },
      { n: 'Julian Ryerson', p: 'DEF', c: 'Borussia Dortmund' },
      { n: 'Kristoffer Ajer', p: 'DEF', c: 'Brentford' },
      { n: 'Leo Østigård', p: 'DEF', c: 'Rennes' },
      { n: 'Stian Gregersen', p: 'DEF', c: 'Mainz 05' },
      { n: 'David Møller Wolfe', p: 'DEF', c: 'AZ Alkmaar' },
      { n: 'Marcus Holmgren Pedersen', p: 'DEF', c: 'Sassuolo' },
      { n: 'Andreas Hanche-Olsen', p: 'DEF', c: 'Mainz 05' },
      { n: 'Martin Ødegaard', p: 'MID', c: 'Arsenal' },
      { n: 'Sander Berge', p: 'MID', c: 'Fulham' },
      { n: 'Patrick Berg', p: 'MID', c: 'Bodø/Glimt' },
      { n: 'Fredrik Aursnes', p: 'MID', c: 'Benfica' },
      { n: 'Morten Thorsby', p: 'MID', c: 'Genoa' },
      { n: 'Aron Dønnum', p: 'MID', c: 'Standard Liège' },
      { n: 'Oscar Bobb', p: 'FWD', c: 'Manchester City' },
      { n: 'Antonio Nusa', p: 'FWD', c: 'RB Leipzig' },
      { n: 'Erling Haaland', p: 'FWD', c: 'Manchester City' },
      { n: 'Alexander Sørloth', p: 'FWD', c: 'Atlético Madrid' },
      { n: 'Jørgen Strand Larsen', p: 'FWD', c: 'Wolverhampton' },
      { n: 'Thelo Aasgaard', p: 'MID', c: 'Rangers' },
      { n: 'Kristian Thorstvedt', p: 'MID', c: 'Sassuolo' },
      { n: 'Mohamed Elyounoussi', p: 'FWD', c: 'FC Copenhagen' },
      { n: 'Sondre Langås', p: 'DEF', c: 'Nordsjælland' },
      { n: 'Ola Brynhildsen', p: 'FWD', c: 'Molde' },
    ],
  },
  // ---------------- GROUP J ----------------
  'Argentina': {
    coach: 'Lionel Scaloni',
    players: [
      { n: 'Emiliano Martínez', p: 'GK', c: 'Aston Villa' },
      { n: 'Gerónimo Rulli', p: 'GK', c: 'Marseille' },
      { n: 'Walter Benítez', p: 'GK', c: 'PSV Eindhoven' },
      { n: 'Nahuel Molina', p: 'DEF', c: 'Atlético Madrid' },
      { n: 'Gonzalo Montiel', p: 'DEF', c: 'River Plate' },
      { n: 'Cristian Romero', p: 'DEF', c: 'Tottenham Hotspur' },
      { n: 'Lisandro Martínez', p: 'DEF', c: 'Manchester United' },
      { n: 'Nicolás Otamendi', p: 'DEF', c: 'Benfica' },
      { n: 'Nicolás Tagliafico', p: 'DEF', c: 'Lyon' },
      { n: 'Marcos Acuña', p: 'DEF', c: 'River Plate' },
      { n: 'Facundo Medina', p: 'DEF', c: 'Marseille' },
      { n: 'Rodrigo De Paul', p: 'MID', c: 'Inter Miami' },
      { n: 'Leandro Paredes', p: 'MID', c: 'Boca Juniors' },
      { n: 'Enzo Fernández', p: 'MID', c: 'Chelsea' },
      { n: 'Alexis Mac Allister', p: 'MID', c: 'Liverpool' },
      { n: 'Exequiel Palacios', p: 'MID', c: 'Bayer Leverkusen' },
      { n: 'Giovani Lo Celso', p: 'MID', c: 'Real Betis' },
      { n: 'Lionel Messi', p: 'FWD', c: 'Inter Miami' },
      { n: 'Julián Álvarez', p: 'FWD', c: 'Atlético Madrid' },
      { n: 'Lautaro Martínez', p: 'FWD', c: 'Inter Milan' },
      { n: 'Nicolás González', p: 'FWD', c: 'Juventus' },
      { n: 'Ángel Di María', p: 'FWD', c: 'Rosario Central' },
      { n: 'Giuliano Simeone', p: 'FWD', c: 'Atlético Madrid' },
      { n: 'Thiago Almada', p: 'MID', c: 'Atlético Madrid' },
      { n: 'Alejandro Garnacho', p: 'FWD', c: 'Chelsea' },
      { n: 'Valentín Carboni', p: 'MID', c: 'Inter Milan' },
    ],
  },
  'Algeria': {
    coach: 'Vladimir Petković',
    players: [
      { n: 'Alexandre Oukidja', p: 'GK', c: 'Metz' },
      { n: 'Luca Zidane', p: 'GK', c: 'Granada' },
      { n: 'Anthony Mandrea', p: 'GK', c: 'Angers' },
      { n: 'Aïssa Mandi', p: 'DEF', c: 'Lille' },
      { n: 'Ramy Bensebaini', p: 'DEF', c: 'Borussia Dortmund' },
      { n: 'Youcef Atal', p: 'DEF', c: 'Al-Sadd' },
      { n: 'Mohamed Amine Tougai', p: 'DEF', c: 'Espérance' },
      { n: 'Jaouen Hadjam', p: 'DEF', c: 'Young Boys' },
      { n: 'Ahmed Touba', p: 'DEF', c: 'Lecce' },
      { n: 'Rayan Aït-Nouri', p: 'DEF', c: 'Manchester City' },
      { n: 'Nabil Bentaleb', p: 'MID', c: 'Lille' },
      { n: 'Ramiz Zerrouki', p: 'MID', c: 'Feyenoord' },
      { n: 'Ismaël Bennacer', p: 'MID', c: 'AC Milan' },
      { n: 'Houssem Aouar', p: 'MID', c: 'Roma' },
      { n: 'Adem Zorgane', p: 'MID', c: 'Charleroi' },
      { n: 'Himad Abdelli', p: 'MID', c: 'Angers' },
      { n: 'Riyad Mahrez', p: 'FWD', c: 'Al-Ahli' },
      { n: 'Saïd Benrahma', p: 'FWD', c: 'Neom SC' },
      { n: 'Yacine Brahimi', p: 'FWD', c: 'Al-Gharafa' },
      { n: 'Amine Gouiri', p: 'FWD', c: 'Marseille' },
      { n: 'Mohamed Amoura', p: 'FWD', c: 'Wolfsburg' },
      { n: 'Baghdad Bounedjah', p: 'FWD', c: 'Al-Sadd' },
      { n: 'Islam Slimani', p: 'FWD', c: 'CR Belouizdad' },
      { n: 'Badredine Bouanani', p: 'FWD', c: 'Nice' },
      { n: 'Farès Chaïbi', p: 'MID', c: 'Eintracht Frankfurt' },
      { n: 'Anis Hadj Moussa', p: 'FWD', c: 'Feyenoord' },
    ],
  },
  'Austria': {
    coach: 'Ralf Rangnick',
    players: [
      { n: 'Patrick Pentz', p: 'GK', c: 'Brøndby' },
      { n: 'Niklas Hedl', p: 'GK', c: 'Rapid Wien' },
      { n: 'Heinz Lindner', p: 'GK', c: 'Union Saint-Gilloise' },
      { n: 'Maximilian Wöber', p: 'DEF', c: "Borussia Mönchengladbach" },
      { n: 'Kevin Danso', p: 'DEF', c: 'Tottenham Hotspur' },
      { n: 'Philipp Lienhart', p: 'DEF', c: 'Freiburg' },
      { n: 'Gernot Trauner', p: 'DEF', c: 'Feyenoord' },
      { n: 'Stefan Posch', p: 'DEF', c: 'Bologna' },
      { n: 'Phillipp Mwene', p: 'DEF', c: 'Mainz 05' },
      { n: 'Flavius Daniliuc', p: 'DEF', c: 'Salernitana' },
      { n: 'Konrad Laimer', p: 'MID', c: 'Bayern Munich' },
      { n: 'Nicolas Seiwald', p: 'MID', c: 'RB Leipzig' },
      { n: 'Florian Grillitsch', p: 'MID', c: 'Hoffenheim' },
      { n: 'Marcel Sabitzer', p: 'MID', c: 'Borussia Dortmund' },
      { n: 'Christoph Baumgartner', p: 'MID', c: 'RB Leipzig' },
      { n: 'Romano Schmid', p: 'MID', c: 'Werder Bremen' },
      { n: 'Patrick Wimmer', p: 'MID', c: 'Wolfsburg' },
      { n: 'Alexander Prass', p: 'MID', c: 'Hoffenheim' },
      { n: 'Marko Arnautović', p: 'FWD', c: 'Belgrade' },
      { n: 'Michael Gregoritsch', p: 'FWD', c: 'Freiburg' },
      { n: 'Marco Friedl', p: 'DEF', c: 'Werder Bremen' },
      { n: 'Maximilian Entrup', p: 'FWD', c: 'Hartberg' },
      { n: 'Junior Adamu', p: 'FWD', c: 'Freiburg' },
      { n: 'Patrick Schmidt', p: 'FWD', c: 'Darmstadt' },
      { n: 'Nikolaus Wurmbrand', p: 'MID', c: 'LASK' },
      { n: 'Matthias Seidl', p: 'MID', c: 'Rapid Wien' },
    ],
  },
  'Jordan': {
    coach: 'Jamal Sellami',
    players: [
      { n: 'Yazeed Abulaila', p: 'GK', c: 'Al-Ramtha' },
      { n: 'Abdullah Al-Fakhouri', p: 'GK', c: 'Al-Wehdat' },
      { n: 'Moataz Yaseen', p: 'GK', c: 'Al-Hussein' },
      { n: 'Mohammad Abu Hasheesh', p: 'DEF', c: 'Al-Wehdat' },
      { n: 'Yazan Al-Arab', p: 'DEF', c: 'Al-Wehdat' },
      { n: 'Abdallah Nasib', p: 'DEF', c: 'Al-Faisaly' },
      { n: 'Salem Al-Ajalin', p: 'DEF', c: 'Al-Hussein' },
      { n: 'Ihsan Haddad', p: 'DEF', c: 'Al-Wehdat' },
      { n: 'Bara Marei', p: 'DEF', c: 'Al-Faisaly' },
      { n: 'Mahmoud Al-Mardi', p: 'DEF', c: 'Al-Ramtha' },
      { n: 'Noor Al-Rawabdeh', p: 'MID', c: 'Al-Faisaly' },
      { n: 'Nizar Al-Rashdan', p: 'MID', c: 'Al-Wehdat' },
      { n: 'Abdallah Jaber', p: 'MID', c: 'Al-Wehdat' },
      { n: 'Mahmoud Al-Mawas', p: 'MID', c: 'Al-Wehdat' },
      { n: 'Yazan Al-Naimat', p: 'FWD', c: 'Al-Ahli' },
      { n: 'Musa Al-Taamari', p: 'FWD', c: 'Montpellier' },
      { n: 'Ali Olwan', p: 'FWD', c: 'Zakho' },
      { n: 'Mohammad Abu Zraiq', p: 'FWD', c: 'Al-Hussein' },
      { n: 'Yousef Abu Jalboush', p: 'GK', c: 'Al-Faisaly' },
      { n: 'Hamza Al-Dardour', p: 'FWD', c: 'Al-Salt' },
      { n: 'Saleh Rateb', p: 'MID', c: 'Al-Faisaly' },
      { n: 'Rajaei Ayed', p: 'MID', c: 'Al-Wehdat' },
      { n: 'Abdallah Al-Naqbi', p: 'DEF', c: 'Al-Jazeera' },
      { n: 'Anas Bani Yaseen', p: 'DEF', c: 'Al-Wehdat' },
      { n: 'Mahmoud Madanat', p: 'FWD', c: 'Al-Wehdat' },
      { n: 'Mahmoud Zoubi', p: 'MID', c: 'Al-Hussein' },
    ],
  },
  // ---------------- GROUP K ----------------
  'Portugal': {
    coach: 'Roberto Martínez',
    players: [
      { n: 'Diogo Costa', p: 'GK', c: 'Porto' },
      { n: 'José Sá', p: 'GK', c: 'Wolverhampton' },
      { n: 'Rui Silva', p: 'GK', c: 'Real Betis' },
      { n: 'João Cancelo', p: 'DEF', c: 'Al-Hilal' },
      { n: 'Diogo Dalot', p: 'DEF', c: 'Manchester United' },
      { n: 'Rúben Dias', p: 'DEF', c: 'Manchester City' },
      { n: 'Gonçalo Inácio', p: 'DEF', c: 'Sporting CP' },
      { n: 'António Silva', p: 'DEF', c: 'Benfica' },
      { n: 'Nuno Mendes', p: 'DEF', c: 'Paris Saint-Germain' },
      { n: 'Rúben Neves', p: 'MID', c: 'Al-Hilal' },
      { n: 'João Palhinha', p: 'MID', c: 'Tottenham Hotspur' },
      { n: 'Vitinha', p: 'MID', c: 'Paris Saint-Germain' },
      { n: 'João Neves', p: 'MID', c: 'Paris Saint-Germain' },
      { n: 'Bruno Fernandes', p: 'MID', c: 'Manchester United' },
      { n: 'Bernardo Silva', p: 'MID', c: 'Manchester City' },
      { n: 'Rúben Loftus-Cheek', p: 'MID', c: 'Milan' },
      { n: 'Cristiano Ronaldo', p: 'FWD', c: 'Al-Nassr' },
      { n: 'Rafael Leão', p: 'FWD', c: 'AC Milan' },
      { n: 'Pedro Gonçalves', p: 'MID', c: 'Sporting CP' },
      { n: 'Pedro Neto', p: 'FWD', c: 'Chelsea' },
      { n: 'Francisco Trincão', p: 'FWD', c: 'Sporting CP' },
      { n: 'Gonçalo Ramos', p: 'FWD', c: 'Paris Saint-Germain' },
      { n: 'João Félix', p: 'FWD', c: 'Al-Nassr' },
      { n: 'Diogo Jota', p: 'FWD', c: 'Liverpool' },
      { n: 'Geovany Quenda', p: 'FWD', c: 'Sporting CP' },
      { n: 'Renato Veiga', p: 'DEF', c: 'Villarreal' },
    ],
  },
  'DR Congo': {
    coach: 'Sébastien Desabre',
    players: [
      { n: 'Lionel Mpasi', p: 'GK', c: 'Rodez' },
      { n: 'Timothy Fayulu', p: 'GK', c: 'Sion' },
      { n: 'Dimitry Bertaud', p: 'GK', c: 'Montpellier' },
      { n: 'Chancel Mbemba', p: 'DEF', c: 'Lille' },
      { n: 'Gédéon Kalulu', p: 'DEF', c: 'Lorient' },
      { n: 'Arthur Masuaku', p: 'DEF', c: 'Sunderland' },
      { n: 'Dylan Batubinsika', p: 'DEF', c: 'Saint-Étienne' },
      { n: 'Aaron Wan-Bissaka', p: 'DEF', c: 'West Ham United' },
      { n: 'Joris Kayembe', p: 'DEF', c: 'Genk' },
      { n: 'Henock Inonga', p: 'DEF', c: 'Mechelen' },
      { n: 'Samuel Moutoussamy', p: 'MID', c: 'Nantes' },
      { n: 'Charles Pickel', p: 'MID', c: 'Cremonese' },
      { n: 'Aaron Tshibola', p: 'MID', c: 'Hapoel Beer Sheva' },
      { n: 'Edo Kayembe', p: 'MID', c: 'Watford' },
      { n: 'Noah Sadiki', p: 'MID', c: 'Sunderland' },
      { n: 'Brian Cipenga', p: 'MID', c: 'Lommel' },
      { n: 'Cédric Bakambu', p: 'FWD', c: 'Real Betis' },
      { n: 'Yoane Wissa', p: 'FWD', c: 'Newcastle United' },
      { n: 'Silas Katompa', p: 'FWD', c: 'Stuttgart' },
      { n: 'Théo Bongonda', p: 'FWD', c: 'Spartak Moscow' },
      { n: 'Meschack Elia', p: 'FWD', c: 'Young Boys' },
      { n: 'Fiston Mayele', p: 'FWD', c: 'Pyramids' },
      { n: 'Simon Banza', p: 'FWD', c: 'Rennes' },
      { n: 'Grady Diangana', p: 'FWD', c: 'West Bromwich Albion' },
      { n: 'Gaël Kakuta', p: 'MID', c: 'Amiens' },
      { n: 'Glody Lilepo', p: 'FWD', c: 'RWD Molenbeek' },
    ],
  },
  'Uzbekistan': {
    coach: 'Timur Kapadze',
    players: [
      { n: 'Utkir Yusupov', p: 'GK', c: 'Pakhtakor' },
      { n: 'Abduvohid Nematov', p: 'GK', c: 'Navbahor' },
      { n: 'Vladimir Nazarov', p: 'GK', c: 'Nasaf' },
      { n: 'Abdukodir Khusanov', p: 'DEF', c: 'Manchester City' },
      { n: 'Rustamjon Ashurmatov', p: 'DEF', c: 'Al-Fayha' },
      { n: 'Farrukh Sayfiev', p: 'DEF', c: 'Pakhtakor' },
      { n: 'Khojiakbar Alijonov', p: 'DEF', c: 'Pakhtakor' },
      { n: 'Sherzod Nasrullaev', p: 'DEF', c: 'Pakhtakor' },
      { n: 'Abdurauf Buriev', p: 'DEF', c: 'Navbahor' },
      { n: 'Umar Eshmurodov', p: 'DEF', c: 'Nasaf' },
      { n: 'Jaloliddin Masharipov', p: 'MID', c: 'Pakhtakor' },
      { n: 'Otabek Shukurov', p: 'MID', c: 'Al-Wakrah' },
      { n: 'Abbosbek Fayzullaev', p: 'MID', c: 'CSKA Moscow' },
      { n: 'Azizbek Turgunboev', p: 'MID', c: 'Pakhtakor' },
      { n: 'Jasurbek Jaloliddinov', p: 'MID', c: 'Lokomotiv Moscow' },
      { n: 'Ostonqul Tashqulov', p: 'MID', c: 'Nasaf' },
      { n: 'Odiljon Hamrobekov', p: 'MID', c: 'Nasaf' },
      { n: 'Eldor Shomurodov', p: 'FWD', c: 'Roma' },
      { n: 'Igor Sergeev', p: 'FWD', c: 'Pakhtakor' },
      { n: 'Khojimat Erkinov', p: 'FWD', c: 'Pakhtakor' },
      { n: 'Bobir Abdixolikov', p: 'FWD', c: 'Al-Najma' },
      { n: 'Oston Urunov', p: 'FWD', c: 'Pari Nizhny Novgorod' },
      { n: 'Sardor Kulmatov', p: 'MID', c: 'Pakhtakor' },
      { n: 'Diyor Kholmatov', p: 'MID', c: 'Pakhtakor' },
      { n: 'Ulugbek Khoshimov', p: 'FWD', c: 'Navbahor' },
      { n: 'Husniddin Aliqulov', p: 'DEF', c: 'Pakhtakor' },
    ],
  },
  'Colombia': {
    coach: 'Néstor Lorenzo',
    players: [
      { n: 'Camilo Vargas', p: 'GK', c: 'Atlas' },
      { n: 'David Ospina', p: 'GK', c: 'Atlético Nacional' },
      { n: 'Álvaro Montero', p: 'GK', c: 'Vélez Sarsfield' },
      { n: 'Daniel Muñoz', p: 'DEF', c: 'Crystal Palace' },
      { n: 'Santiago Arias', p: 'DEF', c: 'Bahia' },
      { n: 'Yerry Mina', p: 'DEF', c: 'Cagliari' },
      { n: 'Dávinson Sánchez', p: 'DEF', c: 'Galatasaray' },
      { n: 'Carlos Cuesta', p: 'DEF', c: 'Galatasaray' },
      { n: 'Johan Mojica', p: 'DEF', c: 'Mallorca' },
      { n: 'Jhon Lucumí', p: 'DEF', c: 'Bologna' },
      { n: 'Deiver Machado', p: 'DEF', c: 'Lens' },
      { n: 'Richard Ríos', p: 'MID', c: 'Benfica' },
      { n: 'Jefferson Lerma', p: 'MID', c: 'Crystal Palace' },
      { n: 'Kevin Castaño', p: 'MID', c: 'River Plate' },
      { n: 'James Rodríguez', p: 'MID', c: 'León' },
      { n: 'Juan Fernando Quintero', p: 'MID', c: 'River Plate' },
      { n: 'Jorge Carrascal', p: 'MID', c: 'Flamengo' },
      { n: 'Luis Díaz', p: 'FWD', c: 'Bayern Munich' },
      { n: 'Jhon Córdoba', p: 'FWD', c: 'Krasnodar' },
      { n: 'Rafael Santos Borré', p: 'FWD', c: 'Internacional' },
      { n: 'Luis Sinisterra', p: 'FWD', c: 'Cruzeiro' },
      { n: 'Jhon Durán', p: 'FWD', c: 'Fenerbahçe' },
      { n: 'Dayro Moreno', p: 'FWD', c: 'Once Caldas' },
      { n: 'Marino Hinestroza', p: 'FWD', c: 'Atlético Nacional' },
      { n: 'Yaser Asprilla', p: 'MID', c: 'Girona' },
      { n: 'Juan David Cabal', p: 'DEF', c: 'Juventus' },
    ],
  },
  // ---------------- GROUP L ----------------
  'England': {
    coach: 'Thomas Tuchel',
    players: [
      { n: 'Jordan Pickford', p: 'GK', c: 'Everton' },
      { n: 'Dean Henderson', p: 'GK', c: 'Crystal Palace' },
      { n: 'James Trafford', p: 'GK', c: 'Manchester City' },
      { n: 'Reece James', p: 'DEF', c: 'Chelsea' },
      { n: 'Kyle Walker', p: 'DEF', c: 'Burnley' },
      { n: 'John Stones', p: 'DEF', c: 'Manchester City' },
      { n: 'Marc Guéhi', p: 'DEF', c: 'Crystal Palace' },
      { n: 'Ezri Konsa', p: 'DEF', c: 'Aston Villa' },
      { n: 'Levi Colwill', p: 'DEF', c: 'Chelsea' },
      { n: 'Myles Lewis-Skelly', p: 'DEF', c: 'Arsenal' },
      { n: 'Tino Livramento', p: 'DEF', c: 'Newcastle United' },
      { n: 'Declan Rice', p: 'MID', c: 'Arsenal' },
      { n: 'Jude Bellingham', p: 'MID', c: 'Real Madrid' },
      { n: 'Cole Palmer', p: 'MID', c: 'Chelsea' },
      { n: 'Morgan Rogers', p: 'MID', c: 'Aston Villa' },
      { n: 'Elliot Anderson', p: 'MID', c: 'Nottingham Forest' },
      { n: 'Curtis Jones', p: 'MID', c: 'Liverpool' },
      { n: 'Phil Foden', p: 'MID', c: 'Manchester City' },
      { n: 'Bukayo Saka', p: 'FWD', c: 'Arsenal' },
      { n: 'Anthony Gordon', p: 'FWD', c: 'Newcastle United' },
      { n: 'Marcus Rashford', p: 'FWD', c: 'Barcelona' },
      { n: 'Harry Kane', p: 'FWD', c: 'Bayern Munich' },
      { n: 'Ollie Watkins', p: 'FWD', c: 'Aston Villa' },
      { n: 'Eberechi Eze', p: 'FWD', c: 'Arsenal' },
      { n: 'Jarrod Bowen', p: 'FWD', c: 'West Ham United' },
      { n: 'Noni Madueke', p: 'FWD', c: 'Arsenal' },
    ],
  },
  'Croatia': {
    coach: 'Zlatko Dalić',
    players: [
      { n: 'Dominik Livaković', p: 'GK', c: 'Girona' },
      { n: 'Ivica Ivušić', p: 'GK', c: 'Bari' },
      { n: 'Nediljko Labrović', p: 'GK', c: 'Rijeka' },
      { n: 'Josip Stanišić', p: 'DEF', c: 'Bayern Munich' },
      { n: 'Joško Gvardiol', p: 'DEF', c: 'Manchester City' },
      { n: 'Josip Šutalo', p: 'DEF', c: 'Ajax' },
      { n: 'Marin Pongračić', p: 'DEF', c: 'Fiorentina' },
      { n: 'Borna Sosa', p: 'DEF', c: 'Ajax' },
      { n: 'Domagoj Vida', p: 'DEF', c: 'AEK Athens' },
      { n: 'Josip Juranović', p: 'DEF', c: 'Union Berlin' },
      { n: 'Luka Modrić', p: 'MID', c: 'AC Milan' },
      { n: 'Mateo Kovačić', p: 'MID', c: 'Manchester City' },
      { n: 'Marcelo Brozović', p: 'MID', c: 'Al-Nassr' },
      { n: 'Nikola Vlašić', p: 'MID', c: 'Torino' },
      { n: 'Luka Sučić', p: 'MID', c: 'Real Sociedad' },
      { n: 'Martin Baturina', p: 'MID', c: 'Como' },
      { n: 'Lovro Majer', p: 'MID', c: 'Wolfsburg' },
      { n: 'Mario Pašalić', p: 'MID', c: 'Atalanta' },
      { n: 'Andrej Kramarić', p: 'FWD', c: 'Hoffenheim' },
      { n: 'Ante Budimir', p: 'FWD', c: 'Osasuna' },
      { n: 'Igor Matanović', p: 'FWD', c: 'Eintracht Frankfurt' },
      { n: 'Marco Pašalić', p: 'FWD', c: 'Orlando City' },
      { n: 'Dion Drena Beljo', p: 'FWD', c: 'Augsburg' },
      { n: 'Petar Musa', p: 'FWD', c: 'FC Dallas' },
      { n: 'Franjo Ivanović', p: 'FWD', c: 'Union Saint-Gilloise' },
      { n: 'Kristijan Jakić', p: 'MID', c: 'Hajduk Split' },
    ],
  },
  'Ghana': {
    coach: 'Otto Addo',
    players: [
      { n: 'Lawrence Ati-Zigi', p: 'GK', c: 'St. Gallen' },
      { n: 'Benjamin Asare', p: 'GK', c: 'Hearts of Oak' },
      { n: 'Joseph Anang', p: 'GK', c: 'St. Patrick\'s' },
      { n: 'Alexander Djiku', p: 'DEF', c: 'Fenerbahçe' },
      { n: 'Mohammed Salisu', p: 'DEF', c: 'Monaco' },
      { n: 'Alidu Seidu', p: 'DEF', c: 'Rennes' },
      { n: 'Gideon Mensah', p: 'DEF', c: 'Le Havre' },
      { n: 'Jerome Opoku', p: 'DEF', c: 'İstanbul Başakşehir' },
      { n: 'Razak Simpson', p: 'DEF', c: 'Nordsjælland' },
      { n: 'Kingsley Schindler', p: 'DEF', c: 'Samsunspor' },
      { n: 'Thomas Partey', p: 'MID', c: 'Villarreal' },
      { n: 'Mohammed Kudus', p: 'MID', c: 'Tottenham Hotspur' },
      { n: 'Elisha Owusu', p: 'MID', c: 'Auxerre' },
      { n: 'Lawrence Agyekum', p: 'MID', c: 'Cercle Brugge' },
      { n: 'Salis Abdul Samed', p: 'MID', c: 'Lens' },
      { n: 'Majeed Ashimeru', p: 'MID', c: 'Anderlecht' },
      { n: 'Kamaldeen Sulemana', p: 'FWD', c: 'Atalanta' },
      { n: 'Antoine Semenyo', p: 'FWD', c: 'Bournemouth' },
      { n: 'Iñaki Williams', p: 'FWD', c: 'Athletic Bilbao' },
      { n: 'Jordan Ayew', p: 'FWD', c: 'Leicester City' },
      { n: 'Abdul Fatawu Issahaku', p: 'FWD', c: 'Leicester City' },
      { n: 'Ernest Nuamah', p: 'FWD', c: 'Lyon' },
      { n: 'Brandon Thomas-Asante', p: 'FWD', c: 'Coventry City' },
      { n: 'Joseph Paintsil', p: 'FWD', c: 'LA Galaxy' },
      { n: 'Forson Amankwah', p: 'MID', c: 'Salzburg' },
      { n: 'Mohammed Fuseini', p: 'MID', c: 'Mechelen' },
    ],
  },
  'Panama': {
    coach: 'Thomas Christiansen',
    players: [
      { n: 'Orlando Mosquera', p: 'GK', c: 'Al-Wehda' },
      { n: 'José Guerra', p: 'GK', c: 'Plaza Amador' },
      { n: 'Luis Mejía', p: 'GK', c: 'Nacional' },
      { n: 'Michael Amir Murillo', p: 'DEF', c: 'Marseille' },
      { n: 'Fidel Escobar', p: 'DEF', c: 'Naval' },
      { n: 'Andrés Andrade', p: 'DEF', c: 'Colorado Rapids' },
      { n: 'Eric Davis', p: 'DEF', c: 'Hércules' },
      { n: 'César Blackman', p: 'DEF', c: 'Cartaginés' },
      { n: 'Jiovany Ramos', p: 'DEF', c: 'Sporting San Miguelito' },
      { n: 'Carlos Harvey', p: 'MID', c: 'Minnesota United' },
      { n: 'Adalberto Carrasquilla', p: 'MID', c: 'Houston Dynamo' },
      { n: 'Aníbal Godoy', p: 'MID', c: 'San Jose Earthquakes' },
      { n: 'Cristian Martínez', p: 'MID', c: 'Atlético Nacional' },
      { n: 'Edgardo Fariña', p: 'MID', c: 'Plaza Amador' },
      { n: 'Cecilio Waterman', p: 'FWD', c: 'Coquimbo Unido' },
      { n: 'Ismael Díaz', p: 'FWD', c: 'León' },
      { n: 'José Fajardo', p: 'FWD', c: 'Independiente' },
      { n: 'Eduardo Guerrero', p: 'FWD', c: 'Sporting San Miguelito' },
      { n: 'Tomás Rodríguez', p: 'MID', c: 'Dépor Aguila' },
      { n: 'Jorge Gutiérrez', p: 'MID', c: 'Plaza Amador' },
      { n: 'Azarías Londoño', p: 'FWD', c: 'Sporting San Miguelito' },
      { n: 'Christian Reyes', p: 'DEF', c: 'CAI' },
      { n: 'Yoel Bárcenas', p: 'MID', c: 'Real Oviedo' },
      { n: 'Édgar Bárcenas', p: 'MID', c: 'Mazatlán' },
      { n: 'Omar Browne', p: 'FWD', c: 'CAI' },
      { n: 'Abdiel Ayarza', p: 'FWD', c: 'Caracas' },
    ],
  },
  // ---------------- GROUP B ----------------
  'Canada': {
    coach: 'Jesse Marsch',
    players: [
      { n: 'Maxime Crépeau', p: 'GK', c: 'Portland Timbers' },
      { n: 'Dayne St. Clair', p: 'GK', c: 'Minnesota United' },
      { n: 'Tom McGill', p: 'GK', c: 'Brighton' },
      { n: 'Alphonso Davies', p: 'DEF', c: 'Bayern Munich' },
      { n: 'Alistair Johnston', p: 'DEF', c: 'Celtic' },
      { n: 'Moïse Bombito', p: 'DEF', c: 'Nice' },
      { n: 'Derek Cornelius', p: 'DEF', c: 'Marseille' },
      { n: 'Joel Waterman', p: 'DEF', c: 'CF Montréal' },
      { n: 'Kamal Miller', p: 'DEF', c: 'Portland Timbers' },
      { n: 'Richie Laryea', p: 'DEF', c: 'Toronto FC' },
      { n: 'Luc de Fougerolles', p: 'DEF', c: 'Fulham' },
      { n: 'Stephen Eustáquio', p: 'MID', c: 'Porto' },
      { n: 'Ismaël Koné', p: 'MID', c: 'Rennes' },
      { n: 'Mathieu Choinière', p: 'MID', c: 'Grasshoppers' },
      { n: 'Liam Fraser', p: 'MID', c: 'Deportivo La Coruña' },
      { n: 'Nathan Saliba', p: 'MID', c: 'Anderlecht' },
      { n: 'Jonathan Osorio', p: 'MID', c: 'Toronto FC' },
      { n: 'Jacob Shaffelburg', p: 'FWD', c: 'Nashville SC' },
      { n: 'Tajon Buchanan', p: 'FWD', c: 'Villarreal' },
      { n: 'Jonathan David', p: 'FWD', c: 'Juventus' },
      { n: 'Cyle Larin', p: 'FWD', c: 'Mallorca' },
      { n: 'Promise David', p: 'FWD', c: 'Union Saint-Gilloise' },
      { n: 'Liam Millar', p: 'FWD', c: 'Hull City' },
      { n: 'Daniel Jebbison', p: 'FWD', c: 'Bournemouth' },
      { n: 'Theo Bair', p: 'FWD', c: 'Saint-Étienne' },
      { n: 'Ali Ahmed', p: 'MID', c: 'Vancouver Whitecaps' },
    ],
  },
  'Bosnia and Herzegovina': {
    coach: 'Sergej Barbarez',
    players: [
      { n: 'Nikola Vasilj', p: 'GK', c: 'St. Pauli' },
      { n: 'Ibrahim Šehić', p: 'GK', c: 'Tuzla City' },
      { n: 'Vladan Kovačević', p: 'GK', c: 'Sporting CP' },
      { n: 'Sead Kolašinac', p: 'DEF', c: 'Atalanta' },
      { n: 'Amar Dedić', p: 'DEF', c: 'Benfica' },
      { n: 'Nikola Katić', p: 'DEF', c: 'Stuttgart' },
      { n: 'Dennis Hadžikadunić', p: 'DEF', c: 'Hajduk Split' },
      { n: 'Adrian Leon Barišić', p: 'DEF', c: 'Rijeka' },
      { n: 'Adnan Kovačević', p: 'DEF', c: 'Konyaspor' },
      { n: 'Erol Doğan', p: 'DEF', c: 'Eyüpspor' },
      { n: 'Miralem Pjanić', p: 'MID', c: 'CSKA Moscow' },
      { n: 'Edin Cocalić', p: 'MID', c: 'Velež Mostar' },
      { n: 'Gojko Cimirot', p: 'MID', c: 'Şanlıurfaspor' },
      { n: 'Benjamin Tahirović', p: 'MID', c: 'Ajax' },
      { n: 'Amar Memić', p: 'MID', c: 'Hannover 96' },
      { n: 'Dženis Burnić', p: 'MID', c: 'Sturm Graz' },
      { n: 'Ivan Bašić', p: 'MID', c: 'Borac Banja Luka' },
      { n: 'Edin Džeko', p: 'FWD', c: 'Fiorentina' },
      { n: 'Ermedin Demirović', p: 'FWD', c: 'Stuttgart' },
      { n: 'Smail Prevljak', p: 'FWD', c: 'Al-Wehda' },
      { n: 'Haris Tabaković', p: 'FWD', c: 'Hoffenheim' },
      { n: 'Armin Gigović', p: 'MID', c: 'Rostov' },
      { n: 'Nedim Bajrami', p: 'MID', c: 'Sassuolo' },
      { n: 'Faris Hajradinović', p: 'MID', c: 'Hatayspor' },
      { n: 'Said Hamulić', p: 'FWD', c: 'Toulouse' },
      { n: 'Dal Varešanović', p: 'MID', c: 'Pisa' },
    ],
  },
  'Qatar': {
    coach: 'Julen Lopetegui',
    players: [
      { n: 'Meshaal Barsham', p: 'GK', c: 'Al-Sadd' },
      { n: 'Saad Al-Sheeb', p: 'GK', c: 'Al-Sadd' },
      { n: 'Yousef Hassan', p: 'GK', c: 'Al-Gharafa' },
      { n: 'Pedro Miguel', p: 'DEF', c: 'Al-Sadd' },
      { n: 'Boualem Khoukhi', p: 'DEF', c: 'Al-Sadd' },
      { n: 'Tarek Salman', p: 'DEF', c: 'Al-Sadd' },
      { n: 'Bassam Al-Rawi', p: 'DEF', c: 'Al-Duhail' },
      { n: 'Jassem Gaber', p: 'DEF', c: 'Al-Arabi' },
      { n: 'Sultan Al-Brake', p: 'DEF', c: 'Al-Duhail' },
      { n: 'Homam Ahmed', p: 'DEF', c: 'Al-Gharafa' },
      { n: 'Karim Boudiaf', p: 'MID', c: 'Al-Duhail' },
      { n: 'Abdulaziz Hatem', p: 'MID', c: 'Al-Rayyan' },
      { n: 'Assim Madibo', p: 'MID', c: 'Al-Duhail' },
      { n: 'Mohammed Waad', p: 'MID', c: 'Al-Sadd' },
      { n: 'Jassem Al-Sharshani', p: 'MID', c: 'Al-Gharafa' },
      { n: 'Ahmed Fadel', p: 'MID', c: 'Al-Wakrah' },
      { n: 'Mostafa Tarek Meshaal', p: 'MID', c: 'Al-Sadd' },
      { n: 'Akram Afif', p: 'FWD', c: 'Al-Sadd' },
      { n: 'Almoez Ali', p: 'FWD', c: 'Al-Duhail' },
      { n: 'Hassan Al-Haydos', p: 'FWD', c: 'Al-Sadd' },
      { n: 'Yusuf Abdurisag', p: 'FWD', c: 'Al-Sadd' },
      { n: 'Ahmed Alaaeldin', p: 'FWD', c: 'Al-Gharafa' },
      { n: 'Mohammed Muntari', p: 'FWD', c: 'Al-Duhail' },
      { n: 'Khaled Muneer', p: 'FWD', c: 'Al-Rayyan' },
      { n: 'Ismail Mohamad', p: 'DEF', c: 'Al-Duhail' },
      { n: 'Tameem Al-Abdullah', p: 'MID', c: 'Al-Rayyan' },
    ],
  },
  'Switzerland': {
    coach: 'Murat Yakin',
    players: [
      { n: 'Gregor Kobel', p: 'GK', c: 'Borussia Dortmund' },
      { n: 'Yvon Mvogo', p: 'GK', c: 'Lorient' },
      { n: 'Marvin Keller', p: 'GK', c: 'Young Boys' },
      { n: 'Manuel Akanji', p: 'DEF', c: 'Inter Milan' },
      { n: 'Nico Elvedi', p: 'DEF', c: "Borussia Mönchengladbach" },
      { n: 'Ricardo Rodríguez', p: 'DEF', c: 'Real Betis' },
      { n: 'Silvan Widmer', p: 'DEF', c: 'Mainz 05' },
      { n: 'Miro Muheim', p: 'DEF', c: 'Hamburger SV' },
      { n: 'Aurèle Amenda', p: 'DEF', c: 'Eintracht Frankfurt' },
      { n: 'Eray Cömert', p: 'DEF', c: 'Valencia' },
      { n: 'Luca Jaquez', p: 'DEF', c: 'Stuttgart' },
      { n: 'Granit Xhaka', p: 'MID', c: 'Sunderland' },
      { n: 'Johan Manzambi', p: 'MID', c: 'Freiburg' },
      { n: 'Remo Freuler', p: 'MID', c: 'Bologna' },
      { n: 'Denis Zakaria', p: 'MID', c: 'Monaco' },
      { n: 'Ardon Jashari', p: 'MID', c: 'AC Milan' },
      { n: 'Djibril Sow', p: 'MID', c: 'Sevilla' },
      { n: 'Christian Fassnacht', p: 'MID', c: 'Young Boys' },
      { n: 'Michel Aebischer', p: 'MID', c: 'Pisa' },
      { n: 'Fabian Rieder', p: 'MID', c: 'Augsburg' },
      { n: 'Rubén Vargas', p: 'MID', c: 'Sevilla' },
      { n: 'Breel Embolo', p: 'FWD', c: 'Rennes' },
      { n: 'Noah Okafor', p: 'FWD', c: 'Leeds United' },
      { n: 'Dan Ndoye', p: 'FWD', c: 'Nottingham Forest' },
      { n: 'Zeki Amdouni', p: 'FWD', c: 'Burnley' },
      { n: 'Cedric Itten', p: 'FWD', c: 'Fortuna Düsseldorf' },
    ],
  },
  // END SQUADS
};
